<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * 
 * Greek Translation Project initiated : 13 February 2014
 * Repository : https://github.com/cerebrux/vtiger6-greek-translation
 * Author(s):
 *  -- Salih Emin (http://www.linkedin.com/in/salihemin)
 *  -- Mathias Stavrou (http://mstavrou.com/)
 *  -- Konstantinos Paraskeuopoulos (https://www.linkedin.com/in/kparaskevopoulos)
 *  -- Dimitris Anagnostou
 *  -- More: https://github.com/cerebrux/vtiger6-greek-translation/graphs/contributors
 *************************************************************************************/
$languageStrings = array(
	'ADD_RULES'					   => 'Add Rules',	
	'After Scan'                   => 'Μετά την σάρωση',
	'MailConverter'                => 'Μετατροπέας Ηλεκτρονικού Ταχυδρομείου',
	'MailConverter_Description'    => 'Μετατρέψει τα ηλεκτρονικά ταχυδρομεία με τις αντίστοιχες εγγραφές',
	'MAILBOX'                      => 'Γραμματοκιβώτιο',
	'RULE'                         => 'Κανόνας',
	'LBL_ADD_RECORD'               => 'Προσθήκη Γραμματοκιβώτιο',
	'ALL'                          => 'Όλα',
	'UNSEEN'                       => 'Αδιάβαστα',
	'LBL_MARK_READ'                => 'Μαρκαρισμένα ως Διαβασμένα',
	'SEEN'                         => 'Διαβασμένα',
	'LBL_EDIT_MAILBOX'             => 'Επεξεργασία Γραμματοκιβωτίου',
	'LBL_CREATE_MAILBOX'           => 'Δημιουργία Γραμματοκιβωτίου',
	'LBL_BACK_TO_MAILBOXES'        => 'Πίσω στο Γραμματοκιβώτιο',
	'LBL_MARK_MESSAGE_AS'          => 'Επισήμανση μηνύματος ως',
	'LBL_MAX_LIMIT_ONLY_TWO'       => 'Μπορείτε να ρυθμίσετε μόνο δύο γραμματοκιβώτια',
	'LBL_IS_IN_RUNNING_STATE'      => 'βρίσκεται σε κατάσταση λειτουργίας',
	'LBL_SAVED_SUCCESSFULLY'       => 'αποθηκεύτηκε με επιτυχία',
	'LBL_ADDING_NEW_MAILBOX' => 'Προσθήκη νέου Γραμμτοκιβωτίου',	
	'LBL_CONNECTION_ERROR' => 'Η σύνδεση με το γραμματοκιβώτιο απέτυχε. Ελέγξτε την δικτυακή συνδεσή σας και δοκιμάστε ξανά.', 	
	'LBL_CONNECTION_TO_MAILBOX_FAILED' => 'Η Σύνδεση με το γραμματοκιβώτιο απέτυχε!',
	'LBL_DELETED_SUCCESSFULLY'     => 'Διαγράφηκε με Επιτυχία',
	'LBL_RULE' => 'Κανόνας',	
	'LBL_RULE_DELETION_FAILED'     => 'Η διαγραφή του κανόνα απέτυχε',
	'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'Οι Πληροφορίες Αλληλουχίας των κανόνων είναι άδειες',
	'LBL_SEQUENCE_UPDATED_SUCCESSFULLY' => 'Η Ακολουθία ενημερώθηκε με επιτυχία',
	'LBL_SCANNED_SUCCESSFULLY'     => 'σαρώθηκε με επιτυχία',
	'LBL_CONDITIONS' => 'Συνθήκες',	
	'Scanner Name'                  => 'Όνομα σάρωσης',
	'Server'                       => 'Όνομα διακομιστή',
	'Protocol'                     => 'Πρωτόκολλο',
	'Password'                     => 'Κωδικός',
	'connecturl'                   => 'Σύνδεση Url',
	'searchfor'                    => 'Ψάξε για',
	'markas'                       => 'Μετά την σάρωση',
	'LBL_CREATE_MAILBOX_NOW'	=> 'Δημιουργία Γραμματοκ. τώρα',
	'LBL_MAILBOX' 			=> 'Γραμματοκυβότιο',    
	'LBL_ENABLE'                   => 'Ενεργό',
	'LBL_DISABLE'                  => 'Ανενεργό',
	'LBL_STATUS_MESSAGE'           => 'Ελέγξτε για να γίνει ενεργό',
	'LBL_VALIDATE_SSL_CERTIFICATE' => 'Έγκυρο SSL Πιστοποιητικό',
	'LBL_DO_NOT_VALIDATE_SSL_CERTIFICATE' => 'Μην Επικυρώσετε το SSL Πιστοποιητικό',
	'LBL_FINISH'	               => 'Τέλος',
	'LBL_ALL_MESSAGES_FROM_LAST_SCAN' => 'Όλα τα μηνύματα από την τελευταία σάρωση',
	'LBL_UNREAD_MESSAGES_FROM_LAST_SCAN' => 'Μη αναγνωσμένων μηνυμάτων από την τελευταία σάρωση',
	'LBL_MAILCONVERTER_DESCRIPTION' => "Mail Converter enables you to configure your mailbox to scan your emails and create appropriate entities in Vtiger CRM.<br />You'll also need to define rules to specify what actions should be performed on your emails.<br />Your emails are scanned automatically, unless you've disabled Mail Scanner task in Scheduler. <br /><br /><br />",
	'LBL_FOLDERS_SCANNED'	       => 'Σαρώθηκαν οι φάκελοι',
	'LBL_MARK_MESSAGES_AS_READ'    => 'Σήμανση μηνυμάτων ως αναγνωσμένα',
	'LBL_I_DONT_KNOW'              => 'Δεν Γνωρίζω',
    'LBL_SCAN_NOW'                 => 'Σάρωση τώρα',
	'LBL_NEXT'			           => 'Επόμενο',
	'LBL_RULES_LIST'               => 'Λίστα Κανόνων',
	'LBL_SELECT_FOLDERS'           => 'Επιλογή Φακέλου',
	'LBL_DELETED_SUCCESSFULLY' => 'Η διαγραφή έγινε επιτυχώς',
	'LBL_RULE_DELETION_FAILED'     => 'Η διαγραφή του κανόνα απέτυχε',
	'LBL_SAVED_SUCCESSFULLY' => 'αποθηκεύτηκε με επιτυχία',
	'LBL_SCANED_SUCCESSFULLY' => 'Σαρώθηκε με επιτυχία',
	'LBL_FOLDERS_INFO_IS_EMPTY' => 'Οι Πληροφορίες φακέλου είναι άδειες',
	'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'Οι Πληροφορίες Αλληλουχίας είναι άδειες',
	'LBL_UPDATE_FOLDERS'           => 'Ενημέρωση Φακέλου',
    'fromaddress'                  => 'από',
	'toaddress'                    => 'να',
	'subject'                      => 'αντικείμενο',
	'body'                         => 'σώμα',
	'matchusing'                   => 'ταιριάζει',
	'action'                       => 'ενέργεια',
	'LBL_PRIORITY'                 => 'προτεραιότητα',
	'PRIORITISE_MESSAGE'           => 'Σύρετε το μπλοκ για να δοθεί προτεραιότητα ',
	'LBL_ALL_CONDITIONS'           => 'Όλες οι προϋποθέσεις',
	'LBL_ANY_CONDITIOn'            => 'κάθε Κατάσταση',
	'Contains'                     => 'Περιέχει',
	'Not Contains'                 => 'δεν Περιέχει',
	'Equals'                       => 'ίσο ',
	'Not Equals'                   => 'δεν είναι ίσο',
	'Begins With'                  => 'αρχίζει',
	'Ends With'                    => 'τελειώνει',
	'Regex'                        => 'Regex',
	'CREATE_HelpDesk_FROM'         => 'Δημιουργία Δελτίου Τ.Υ',
	'UPDATE_HelpDesk_SUBJECT'      => 'Ενημέρωση Δελτίου Τ.Υ',
	'LINK_Contacts_FROM'           => 'Προσθήκη στην Επαφή [ΑΠΟ]',
	'LINK_Contacts_TO'             => 'Προσθήκη στην Επαφή [TO]',
	'LINK_Accounts_FROM'           => 'Προσθήκη στο Πελάτη [ΑΠΟ]',
	'LINK_Accounts_TO'             => 'Προσθήκη στο Πελάτη [TO]',
	'LINK_Leads_FROM' => 'Προσθήκη στην προοπτική [ΑΠΟ]',
	'LINK_Leads_TO' => 'Προσθήκη στην προοπτική [ΠΡΟΣ]',	
	'LBL_UPDATE_FOLDERS' => 'Ενημέρωση Φακέλλων',
	'Look For'                     => 'Δες για'	
	'LBL_UNSELECT_ALL'             => 'Αποεπιλογή Όλων',
	'LBL_CONVERT_EMAILS_TO_RESPECTIVE_RECORDS' => 'Μετατρέψει τα ηλεκτρονικά ταχυδρομεία με τις αντίστοιχες εγγραφές',
	'LBL_DRAG_AND_DROP_BLOCK_TO_PRIORITISE_THE_RULE' => 'Σύρετε ουτοσώστε να δοθεί προτεραιότητα του κράτους',
	'LBL_ADD_RULE'                 => 'Προσθήκη Κανόνα',
	'LBL_PRIORITY' 		       => 'Προτεραιότητα',
	'LBL_DELETE_RULE'              => 'Διαγραφή Κανόνα',
	'LBL_BODY'                     => 'Σώμα',
	'LBL_MATCH'                    => 'Ταιριάζει',
	'LBL_ACTION'                   => 'Ενέργεια',
	'LBL_FROM'                     => 'Από',
	'SELECT_FOLDERS' => 'Επιλογή φακέλων',	
	'SSL Method'                   => 'Μέθοδος SSL',	
	'SSL Type'                     => 'Τύπος SSL',	
	'Time Zone'                    => 'Ζώνη ώρας',	
	'TO_CHANGE_THE_FOLDER_SELECTION_DESELECT_ANY_OF_THE_SELECTED_FOLDERS' => 'Για να αλλάξετε την επιλογή φακέλων, αποεπιλέξτε κάποιο απο τους επιλεγμένους φακέλους',	
	'User Name'	                   => 'Όνομα Χρήστη'                   , 	
	'Validate SSL Certificate'     => 'Επικύρωση πιστοποιητικού SSL',
);

$jsLanguageStrings = array(
    'JS_MAILBOX_DELETED_SUCCESSFULLY' => 'Το Γραμματοκιβώτιο διαγράφηκε με επιτυχία',
	'JS_MAILBOX_LOADED_SUCCESSFULLY' => 'Το Γραμματοκιβώτιο Φορτώθηκε με επιτυχία',
);	
