<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * 
 * Greek Translation Project initiated : 13 February 2014
 * Repository : https://github.com/cerebrux/vtiger6-greek-translation
 * Author(s):
 *  -- Salih Emin (http://www.linkedin.com/in/salihemin)
 *  -- Mathias Stavrou (http://mstavrou.com/)
 *  -- Konstantinos Paraskeuopoulos (https://www.linkedin.com/in/kparaskevopoulos)
 *  -- Dimitris Anagnostou
 *  -- More: https://github.com/cerebrux/vtiger6-greek-translation/graphs/contributors
 *************************************************************************************/

$languageStrings = array (
	'MailManager' => 'Διαχείριση Email',
	
	// General translations
	'LBL_Folders'         => 'Φάκελοι',
	'LBL_Newer'           => 'Νεότερα',
	'LBL_Older'           => 'Παλαιότερα',
	'LBL_No_Mails_Found'  => 'Δεν βρέθηκαν email',
	'LBL_Go_Back'         => 'Επιστροφή',
	'LBL_Reply_All'       => 'Απάντηση σε όλους',
	'LBL_Reply'           => 'Απάντηση',
	'LBL_Mark_As_Unread'  => 'Θεώρησε ως μη διαβασμένο',
	'LBL_Previous'        => 'προηγούμενο',
	'LBL_Next'            => 'επόμενο',
	'LBL_RELATED_RECORDS' => 'Σχετικές εγγραφές',
	'LBL_Mailbox'         => 'Γραμματοκιβώτιο',
	'LBL_Outbox'          => 'CRM Outbox',
	'LBL_Like'            => 'όπως',
	'LBL_Mail_Server'     => 'Όνομα εξυπηρετητή ή διεύθυνση IP',
	'LBL_Refresh'         => 'Ανανέωση',
	'LBL_Cancel'          => 'Ακύρωσης',
	'LBL_Send'            => 'Αποστολή',
	'LBL_Compose'         => 'Σύνθεση',
	'LBL_Forward'         => 'Προώθηση',
	'LBL_Remove'          => 'Διαγραφή',
	'LBL_Associate'       => 'Συσχέτιση',
	'LBL_Create_Contact'  => 'Δημιουργία επαφής',
	'LBL_No_Matching_Record_Found' => 'Δε βρέθηκαν σχετικές εγγραφές.',
	'LBL_ACTIONS'         => 'Επιλογές',
	'LBL_Search'          => 'Αναζήτηση',
	'LBL_Delete'            =>  'Διαγραφή',
	
	'LBL_Username'             => 'Όνομα χρήστη',
	'LBL_Your_Mailbox_Account' => 'Ο λογαριασμός ηλεκτρονικού ταχυδρομείου',
	'LBL_Password'             => 'Συνθηματικό',
	'LBL_Account_Password'     => 'συνθηματικό λογαριασμού',
	'LBL_Protocol'    => 'Πρωτόκολλο',
	'LBL_Imap2'       => 'IMAP2',
	'LBL_Imap4'       => 'IMAP4',
	'LBL_SSL_Options' => 'Επιλογές SSL',
	'LBL_No_TLS'      => 'Όχι TLS',
	'LBL_TLS'         => 'TLS',
	'LBL_SSL'         => 'SSL',
	'LBL_Certificate_Validations' => 'Επικυρώσεις πιστοποιητικού',
	'LBL_Validate_Cert'           => 'Επικύρωση πιστοποιητικού',
	'LBL_Do_Not_Validate_Cert'    => 'Μη επικύρωση πιστοποιητικού',
	'LBL_SELECT_ACCOUNT_TYPE'     => 'Επιλογή τύπου',
	
	'LBL_FROM'        => 'Από',
	'LBL_TO'          => 'Προς',
	'LBL_CC'          => 'Κοινοποίηση',
	'LBL_BCC'         => 'Κρυφή κοινοποίηση',
	'LBL_Date'        => 'Ημερομηνία',
	'LBL_Attachments' => 'Συνημμένα αρχεία',
	'LBL_EMAIL_TEMPLATES_LIST'=>'Πρότυπα email',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Επιλογή προτύπου email',
	'LBL_ATTACHMENTS'  =>'Συνημμένα αρχεία:',
	'LBL_SELECT_DOCUMENTS'=>'Επιλογή εγγράφων',
	'LBL_IN' =>'σε',
	'LBL_FIND'=>'Αναζήτηση',
	'LBL_SAVE_NOW'=>'Αποθήκευση',
	'LBL_Drafts'=>'Πρόχειρα',
 	'LBL_NO_EMAILS_SELECTED' => 'Δεν επιλέχθηκαν email.',
	'LBL_SUBJECT'	=>	'Θέμα',
	'LBL_WRITE_ACCESS_FOR'	=>'Δικαίωμα εγγραφής για',
	'LBL_READ_ACCESS_FOR'	=>'Δικαίωμα ανάγνωσης για',
	'LBL_MODULE_DENIED' => 'ενότητα απορρίφθηκε!',
	'LBL_REFRESH_TIME'=>'Χρόνος ανανέωσης',
	'LBL_NONE' => 'Καμμία επιλογή',
	'LBL_5_MIN' => '5 λεπτά',
	'LBL_10_MIN' => '10 λεπτά',
	'LBL_MOVE_TO'=>'Μετακίνηση σε ...',
    'LBL_MAILMANAGER_ADD_Contacts' => 'Προσθήκη επαφής',
    'LBL_MAILMANAGER_ADD_Accounts' => 'Προσθήκη οργανισμού',
    'LBL_MAILMANAGER_ADD_Leads' => 'Προσθήκη σύστασης',
    'LBL_MAILMANAGER_ADD_Calendar' => 'Προσθήκη εργασίας',
    'LBL_MAILMANAGER_ADD_HelpDesk' => 'Προσθήκη αιτήματος',
    'LBL_MAILMANAGER_ADD_Emails' => 'Επισύναψη email',
    'LBL_MAILMANAGER_ADD_ModComments' => 'Προσθήκη σχολίου',
    'LBL_ADD' => 'Προσθήκη',
	'JSLBL_Body_Cannot_Be_Empty' => 'Το κύριο μέρος δεν μπορεί να είναι κενό',
	'LBL_ALLMAILS' => 'Όλα τα email',
	'LBL_TO_CONTACTS' => 'Στις επαφές',
	'LBL_TO_ACCOUNTS' => 'Στους οργανισμούς',
	'LBL_TO_LEADS' => 'Στις συστάσεις',
	'LBL_TO_USERS' => 'Στους χρήστες',
	'LBL_SENT_MAILS' => 'Απεσταλμένα email',
	'LBL_Print' => 'Εκτύπωση',
	
	'LBL_SAVE_BUTTON_LABEL' => 'Αποθήκευση',
	'LBL_CANCEL_BUTTON_LABEL' => 'Ακύρωση',
	'LBL_CREATE_MAILBOX' => 'Δημιουργία γραμματοκιβωτίου',
	'LBL_WRITE_YOUR_COMMENT_HERE' => 'Πρόσθεσε σχόλιο ...'
);

$jsLanguageStrings = array (
	'MailManager' => 'Διαχείριση Email',
	
	// Translations for JS (please use the prefix JSLBL in key)
	'JSLBL_Loading_Please_Wait'  => 'Φόρτωση email παρακαλώ περιμένετε',
	'JSLBL_Loading'              => 'Φόρτωση',
	'JSLBL_Settings'             => 'Ρυθμίσεις',
	'JSLBL_Opening'              => 'Άνοιγμα',
	'JSLBL_Deleting'              => 'Διαγραφή',  
	'JSLBL_Updating'             => 'Ενημέρωση',
	'JSLBL_Associating'          => 'Συσχέτιση',
	'JSLBL_Saving_And_Verifying' => 'Αποθήκευση και επιβεβαίωση',
	'JSLBL_Failed_To_Open_Mail'  => 'Το email δεν μπόρεσε να ανοιχτεί',
	'JSLBL_Finding_Relation'     => 'Εύρεση συσχέτισης',
	'JSLBL_Find_Relation_Now'    => 'Εύρεση συσχέτισης τώρα',
	'JSLBL_Searching'            => 'Αναζήτηση',
	'JSLBL_Searching_Please_Wait'=> 'Αναζήτηση παρακαλώ περιμένετε',
	'JSLBL_Sending'              => 'Αποστολή',
	'JSLBL_Replied'              => 'Απαντήθηκε',
	'JSLBL_Failed_To_Send_Mail'  => 'Η αποστολή του email απέτυχε',
	'JSLBL_Recepient_Cannot_Be_Empty' => 'Ο αποδέκτης δεν μπορεί να είναι κενός',
	'JSLBL_Subject_Cannot_Be_Empty'     => 'Το θέμα δε μπορεί να είναι κενό',
	'JSLBL_Removing'                  => 'Απομάκρυνση',
	'JSLBL_Choose_Server_Type'        => 'Επιλογή τύπου εξυπηρετητή',
	'JSLBL_Other'                     => 'Άλλη',
	'JSLBL_Gmail'                     => 'Gmail',
	'JSLBL_Fastmail'                  => 'Fastmail',
	'JSLBL_Search_For_Email'          => 'Αναζήτηση email',
	'JSLBL_Nothing_Found'             => 'Δεν βρέθηκαν',
	'JSLBL_Delete_Confirm'            =>'Θέλετε να διαγράψετε τα email οριστικά;',
	'JSLBL_Delete_Mails_Confirm'      =>'Θέλετε να διαγράψετε τα email;',
	'JSLBL_Receipents_Warning_Message'=>'Παρακαλώ επιλέξτε αποδέκτες',
	'JSLBL_NO_MATCH'				  => 'Δεν βρέθηκε σύνδεση',
	'JSLBL_Saving'					=> 'Αποθήκευση',
	'JSLBL_Failed_To_Save_Mail'		=>	'Η αποθήκευση του email απέτυχε',
	'JSLBL_ATTACHMENT_NOT_DELETED'	=>	'Το επισυναπτόμενο αρχείο δεν διεγράφη',
	'JSLBL_UPLOAD_CANCEL'	=> 'Ακύρωση',
	'JSLBL_UPLOAD_DROPFILES'=>'Σύρετε αρχεία εδώ για μεταφόρτωση',
	'JSLBL_UPLOAD_FILE'=>'Μεταφόρτωση',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'Απέτυχε',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'Το αρχείο είναι πολύ μεγάλο για μεταφόρτωση!!',
	'JSLBL_MAIL_SENT'=>'Το email εστάλλει',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'Η διεύθυνση email δεν έχει σωστή μορφή',
	'JSLBL_Saving'=>'Αποθήκευση',
	'JSLBL_SaveWith_EmptySubject'=>'Αποθήκευση με κενό θέμα;',
	'JSLBL_Delete'            =>  'Διαγραφή',
	'JSLBL_Drafts'=>'Πρόχειρα',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'Ο κωδικός δεν μπορεί να είναι κενός',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'Ο εξυπηρετητής δεν μπορεί να είναι κενός',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'Το όνομα χρήστη δεν μπορεί να είναι κενό',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'Το όνομα του λογιαριασμού δεν μπορεί να είναι κενό',
	'JSLBL_FROM'=>'Από:',
	'JSLBL_DATE'=>'Ημερομηνία: ',
	'JSLBL_SUBJECT'=>'Θέμα: ',
	'JSLBL_TO'=>'Προς: ',
	'JSLBL_CC'=>'Κοινοποίηση: ',
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'---------- Προωθημένο email ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'Επιλέξτε τουλάχιστον ένα email',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'Επιλέξτε τουλάχιστον μια εγγραφή',
	'JSLBL_MAIL_MOVED'=>'Email μετακινήθηκαν',
	'JSLBL_MOVING'=>'Μετακινη email',
	'JSLBL_LOADING_FOLDERS' => 'Φόρτωση φακέλλων..',
	'JSLBL_ADD_COMMENT'=>'Προσθήκη σχολίου',
    'JSLBL_Yahoo'=>'Yahoo',
    'JSLBL_CANNOT_ADD_EMPTY_COMMENT' => 'Το σχόλιο εν μπορεί να είναι κενό',
    'JSLBL_NO_EMAILS_SELECTED' => 'Δεν επιλεχθηκαν email.',
    'JSLBL_ENTER_SOME_VALUE' => 'Πληκτρολογήστε κάτι για αναζήτηση',
    'JSLBL_DRAFT_MAIL_SAVED'=>'Το Email αποθηκεύτηκε στα πρόχειρα',
);

// Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
