<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

$languageStrings = Array (
	'MailManager' => 'Mail Manager',
	
	// General translations
	'LBL_Folders'         => 'Folders',
	'LBL_Newer'           => 'Newer',
	'LBL_Older'           => 'Older',
	'LBL_No_Mails_Found'  => 'No mails found.',
	'LBL_Go_Back'         => 'Back',
	'LBL_Reply_All'       => 'Reply all',
	'LBL_Reply'           => 'Reply',
	'LBL_Mark_As_Unread'  => 'Mark as unread',
	'LBL_Previous'        => 'previous',
	'LBL_Next'            => 'next',
	'LBL_RELATED_RECORDS' => 'Related Records',
	'LBL_Mailbox'         => 'Mailbox',
	'LBL_Outbox'          => 'CRM Outbox',
	'LBL_Like'            => 'like',
	'LBL_Mail_Server'     => 'Mail Server Name or IP',
	'LBL_Refresh'         => 'Refresh',
	'LBL_Cancel'          => 'Cancel',
	'LBL_Send'            => 'Send',
	'LBL_Compose'         => 'Compose',
	'LBL_Forward'         => 'Forward',
	'LBL_Remove'          => 'Remove',
	'LBL_Associate'       => 'Associate',
	'LBL_Create_Contact'  => 'Create contact',
	'LBL_No_Matching_Record_Found' => 'No matching records found.',
	'LBL_ACTIONS'         => 'Actions',
	'LBL_Search'          => 'Search',
	'LBL_Delete'            =>  'Delete',
	
	'LBL_Username'             => 'User Name',
	'LBL_Your_Mailbox_Account' => 'your mailbox account',
	'LBL_Password'             => 'Password',
	'LBL_Account_Password'     => 'account password',
	'LBL_Protocol'    => 'Protocol',
	'LBL_Imap2'       => 'IMAP2',
	'LBL_Imap4'       => 'IMAP4',
	'LBL_SSL_Options' => 'SSL Options',
	'LBL_No_TLS'      => 'No TLS',
	'LBL_TLS'         => 'TLS',
	'LBL_SSL'         => 'SSL',
	'LBL_Certificate_Validations' => 'Certificate Validations',
	'LBL_Validate_Cert'           => 'Validate cert',
	'LBL_Do_Not_Validate_Cert'    => 'Do not validate cert',
	'LBL_SELECT_ACCOUNT_TYPE'     => 'Select Organization Type',
	
	'LBL_FROM'        => 'From',
	'LBL_TO'          => 'To',
	'LBL_CC'          => 'CC',
	'LBL_BCC'         => 'BCC',
	'LBL_Date'        => 'Date',
	'LBL_Attachments' => 'Attachments',
	'LBL_EMAIL_TEMPLATES_LIST'=>'Email Templates',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Select Email template',
	'LBL_ATTACHMENTS'  =>'Attachment:',
	'LBL_SELECT_DOCUMENTS'=>'Select Documents',
	'LBL_IN' =>'in',
	'LBL_FIND'=>'Find',
	'LBL_SAVE_NOW'=>'Save Now',
	'LBL_Drafts'=>'Drafts',
 	'LBL_NO_EMAILS_SELECTED' => 'No Emails Selected.',
	'LBL_SUBJECT'	=>	'Subject',
	'LBL_WRITE_ACCESS_FOR'	=>'Write access for',
	'LBL_READ_ACCESS_FOR'	=>'Read access for',
	'LBL_MODULE_DENIED' => 'module denied!',
	'LBL_REFRESH_TIME'=>'Refresh Time',
	'LBL_NONE' => 'None',
	'LBL_5_MIN' => '5 Minutes',
	'LBL_10_MIN' => '10 Minutes',
	'LBL_MOVE_TO'=>'Move To...',
    'LBL_MAILMANAGER_ADD_Contacts' => 'Add Contact',
    'LBL_MAILMANAGER_ADD_Accounts' => 'Add Organization',
    'LBL_MAILMANAGER_ADD_Leads' => 'Add Lead',
    'LBL_MAILMANAGER_ADD_Calendar' => 'Add ToDo',
    'LBL_MAILMANAGER_ADD_HelpDesk' => 'Add Ticket',
    'LBL_MAILMANAGER_ADD_Emails' => 'Attach Email',
    'LBL_MAILMANAGER_ADD_ModComments' => 'Add Comment',
    'LBL_ADD' => 'Add',
	'JSLBL_Body_Cannot_Be_Empty' => 'Body cannot be empty',
	'LBL_ALLMAILS' => 'All Mails',
	'LBL_TO_CONTACTS' => 'To Contacts',
	'LBL_TO_ACCOUNTS' => 'To Organizations',
	'LBL_TO_LEADS' => 'To Leads',
	'LBL_TO_USERS' => 'To Users',
	'LBL_SENT_MAILS' => 'Sent Mails',
	'LBL_Print' => 'Print',
	
	'LBL_SAVE_BUTTON_LABEL' => 'Save',
	'LBL_CANCEL_BUTTON_LABEL' => 'Cancel',
	'LBL_CREATE_MAILBOX' => 'Create Mailbox',
	'LBL_WRITE_YOUR_COMMENT_HERE' => 'Add your comment here ...'
);

$jsLanguageStrings = Array (
	'MailManager' => 'Mail Manager', // το αφήνουμε αμετάφραστο ;
	
	// Translations for JS (please use the prefix JSLBL in key)
	'JSLBL_Loading_Please_Wait'  => 'Φωρτώνει Παρακαλώ περιμένετε',
	'JSLBL_Loading'              => 'Φωρτώνει',
	'JSLBL_Settings'             => 'Ρυθμίσεις',
	'JSLBL_Opening'              => 'Άνοιγμα',
	'JSLBL_Deleting'              => 'Διαγράφεται',  
	'JSLBL_Updating'             => 'Ενημερώνεται',
	'JSLBL_Associating'          => 'Συσχετίζεται',
	'JSLBL_Saving_And_Verifying' => 'Αποθήκευση & Επιβεβαίωση',
	'JSLBL_Failed_To_Open_Mail'  => 'Αποτυχία στο άνοιγμα του mail',
	'JSLBL_Finding_Relation'     => 'Έυρεση σχέσης',
	'JSLBL_Find_Relation_Now'    => 'Ευρεση σχέσης τώρα',
	'JSLBL_Searching'            => 'Αναζήτηση',
	'JSLBL_Searching_Please_Wait'=> 'Αναζήτηση Παρακαλώ περιμένετε',
	'JSLBL_Sending'              => 'Αποστολή',
	'JSLBL_Replied'              => 'Απαντήθηκε',
	'JSLBL_Failed_To_Send_Mail'  => 'Αποτυχία στην αποστολή του mail',
	'JSLBL_Recepient_Cannot_Be_Empty' => 'Το πεδίο παραλύπτη (Προς) δεν μπορεί να είναι κενό',
	'JSLBL_Subject_Cannot_Be_Empty'     => 'Το πεδίο Θέματος δεν μπορεί να είναι κενό',
	'JSLBL_Removing'                  => 'Αφαίρεση',
	'JSLBL_Choose_Server_Type'        => 'Επιλέξτε τύπο διακομιστή',
	'JSLBL_Other'                     => 'Άλλα',
	'JSLBL_Gmail'                     => 'Gmail',
	'JSLBL_Fastmail'                  => 'Fastmail',
	'JSLBL_Search_For_Email'          => 'Αναζήτηση για email',
	'JSLBL_Nothing_Found'             => 'Nothing found',
	'JSLBL_Delete_Confirm'            =>'Θέλετε να διαγράψετε τα Email μόνιμα;',
	'JSLBL_Delete_Mails_Confirm'      =>'Θέλετε να διαγράψετε τα Email;',
	'JSLBL_Receipents_Warning_Message'=>'Παρακαλώ επιλέξτε παραλύπτες',
	'JSLBL_NO_MATCH'				  => 'Δεν βρέθηκαν όμοια', // no matching found δεν είμαι σύγουρος για καλύτερη μετάφραση
	'JSLBL_Saving'					=> 'Αποθήκευση',
	'JSLBL_Failed_To_Save_Mail'		=>	'Αποτυχία αποθήκευσης του email',
	'JSLBL_ATTACHMENT_NOT_DELETED'	=>	'Αδυναμία διαγραφής του συνημμένου',
	'JSLBL_UPLOAD_CANCEL'	=> 'Ακύρωση',
	'JSLBL_UPLOAD_DROPFILES'=>'Ρείξτε τα αρχεία εδώ για μεταφόρτωση',
	'JSLBL_UPLOAD_FILE'=>'Μεταφόρτωση',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'Απέτυχε',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'Ξεπεράστηκε το όριο μεγέθους Μεταφόρτωσης!!',
	'JSLBL_MAIL_SENT'=>'Mail Sent',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'Παρακαλώ δώστε σωστή διεύθυνση email',
	'JSLBL_Saving'=>'Αποθήκευση',
	'JSLBL_SaveWith_EmptySubject'=>'Αποθήκευση χωρίς να ορίσετε θέμα;',
	'JSLBL_Delete'            =>  'Διαγραφή',
	'JSLBL_Drafts'=>'Πρόχειρα',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'Το Συνθηματικό δεν μπορεί να είναι κενό',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'Το Όνομα Διακομιστή δεν μπορεί να είναι κενό',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'Το Όνομα Χρήστη δεν μπορεί να είναι κενό',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'Το Όνομα Οργανισμού δεν μπορεί να είναι κενό',
	'JSLBL_FROM'=>'Από:',
	'JSLBL_DATE'=>'Ημερομηνία: ',
	'JSLBL_SUBJECT'=>'Θέμα: ',
	'JSLBL_TO'=>'Πρός: ',
	'JSLBL_CC'=>'Cc: ', // Δεν μεταφράζεται, είναι διεθνός αναγνωρισμένο
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'---------- Προωθημένο μήνυμα ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'Επιλέξτε τουλάχιστον ένα mail',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'Επιλέξτε τουλάχιστον μια εγγραφή',
	'JSLBL_MAIL_MOVED'=>'Τα Mail μετακινήθηκαν',
	'JSLBL_MOVING'=>'Μετακίνηση των Mail',
	'JSLBL_LOADING_FOLDERS' => 'Φώρτωση Φακέλων..',
	'JSLBL_ADD_COMMENT'=>'Προσθήκη Σχολίου',
    'JSLBL_Yahoo'=>'Yahoo',
    'JSLBL_CANNOT_ADD_EMPTY_COMMENT' => 'Το Σχόλιο δεν μπορεί αν είναι κενό',
    'JSLBL_NO_EMAILS_SELECTED' => 'Κανένα Email δεν επιλέγχθηκε.',
    'JSLBL_ENTER_SOME_VALUE' => 'Γράψτε κάτι προς αναζήτηση',
    'JSLBL_DRAFT_MAIL_SAVED'=>'Το Mail αποθηκεύτηκε στα Πρόχειρα',
);

// Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
