<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * 
 * Greek Translation Project initiated : 13 February 2014
 * Repository : https://github.com/cerebrux/vtiger6-greek-translation
 * Author(s):
 *  -- Salih Emin (http://www.linkedin.com/in/salihemin)
 *  -- Mathias Stavrou (http://mstavrou.com/)
 *  -- Konstantinos Paraskeuopoulos (https://www.linkedin.com/in/kparaskevopoulos)
 *  -- Dimitris Anagnostou
 *  -- More: https://github.com/cerebrux/vtiger6-greek-translation/graphs/contributors
 *************************************************************************************/
$languageStrings = array(
	'Account and Contact Reports'=>'Αναφορές Οργανισμών και Επαφών',
	'Accounts Email Report'=>'Αναφορά Email Οργανισμών',
	'Activity Reports'=>'Αναφορές Δραστηριοτήτων',
	'Campaign Expectations and Actuals'=>'Προσδοκίες Εκστρατείώμ και Πραγματοποιήσεις', //Added for Campaigns
	'Campaign Reports'=>'Αναφορές Εκστρατιών', //Added for Campaigns
	'Closed Potentials'=>'Κλειστές Ευκαιρίες',
	'Contacts by Accounts'=>'Επαφές ανά Οργανισμούς',
	'Contacts by Potentials'=>'Επαφές ανά Ευκαιρίες',
	'Contacts Email Report'=>'Αναφορά Email Επαφών',
	'Contacts not related to Accounts'=>'Επαφές μη σχετιζόμενες με Οργανισμούς',
	'Contacts related to Accounts'=>'Επαφές σχετιζόμενες με Οργανισμούς',
	'Contacts related to Potentials'=>'Επαφές σχετιζόμενες με Ευκαιρίες',
	'Contacts without Accounts'=>'Επαφές χωρίς Οργανισμούς',
	'Email Reports'=>'Αναφορές Email',
	'Emails sent to Contacts' => 'Απεσταλμένα Email σε Επαφές',
	'Emails sent to Leads' => 'Απεσταλμένα Email σε Προοπτικές',
	'Emails sent to Organizations' => 'Απεσταλμένα Email σε Οργανισμούς',
	'Emails sent to Vendors' => 'Απεσταλμένα Email σε Προμηθευτές',
	'HelpDesk Reports'=>'Αναφορές Δελτίων Υποστ.',
	'Invoice Detailed Report'=>'Λαπτομερείς Αναφορά Τιμολογίων',
	'Invoice Reports'=>'Αναφορές Τιμολογίων',
	'Last Month Activities'=>'Δραστηριότητες Τελευταίου Μήνα',
	'LBL_ADD_FOLDER' => 'Προσθήκη Φακέλου',
	'LBL_ADD_NEW_FOLDER' => 'Προσθήκη Νέου φακέλου',
	'LBL_ADD_RECORD' => 'Προσθήκη Αναφοράς',
	'LBL_ALL_REPORTS' => 'Όλες οι Αναφορές',
	'LBL_ASCENDING' => 'Αύξουσα',
	'LBL_AT_TIME' => 'Σε χρόνο',
	'LBL_AVERAGE' => 'Μέσος Όρος',
	'LBL_AVG' => 'Μεσ. Ορ',
	'LBL_CALCULATION_CONVERSION_MESSAGE' => 'Οι υπολογισμοί βασίζονται στην Ισοτιμία βάσης του CRM σας',
	'LBL_CALCULATIONS' =>'Υπολογισμοί',
	'LBL_CHOOSE_DATE' => 'Επιλέξτε Ημερομ.',
	'LBL_COLUMNS' => 'Στήλες',
	'LBL_CREATING_REPORT' => 'Δημιουργ. Αναφοράς',
	'LBL_CUSTOMIZE' => 'Προσαρμογή',
	'LBL_DAILY' => 'Ημερίσια',
	'LBL_DENIED_REPORTS' => 'Απορριφθέντες Αναφορές',
	'LBL_DESCENDING' => 'Φθίνουσα',
	'LBL_DESCRIPTION' => 'Περιγραφή',
	'LBL_DUPLICATES_EXIST' => 'Το Όνομα Αναφοράς υπάρχει ήδη',
	'LBL_EDITING_REPORT' => 'Επεξεργασία',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Ξεπεράστικε το ανώτατο όριο',	
	'LBL_FIELD_NAMES' => 'Ονόματα Πεδίων',
	'LBL_FILTERS' => 'Φίλτρα',
	'LBL_FOLDER_CAN_NOT_BE_DELETED' => 'Αυτός ο φάκελος δεν μπορεί να διαγραφεί',
	'LBL_FOLDER_DESCRIPTION' => 'Περιγραφή Φακέλου',
	'LBL_FOLDER_NAME' => 'Όνομα Φακέλου',
	'LBL_FOLDER_NOT_EMPTY' => 'Ο φάκελος δεν είναι κενός',
	'LBL_FOLDERS' => 'Φάκελοι',
	'LBL_FOLDERS_LIST' => 'Λίστα Φακέλων',
	'LBL_GENERATE_NOW' => 'Δημιουργία τώρα',
	'LBL_GENERATE_REPORT' => 'Δημιουργία Αναφοράς',
	'LBL_GROUP_BY' => 'Ομαδοποίηση κατά',
	'LBL_HIGHEST_VALUE' => 'Υψηλότερη τιμή',
	'LBL_LIMIT_EXCEEDED' => 'Μόνο 1000 + εγγραφές προβάλλονται. Χρησιμοποιείστε τις επιλογές CSV η Εξαγωγή σε Excel για να δείτε όλες τις εγγραφές',
	'LBL_LOWEST_VALUE' => 'Χαμηλότερη Τιμή',
	'LBL_MAX' => 'Μέγιστο',
	'LBL_MIN' => 'Ελάχιστο',
	'LBL_MONTHLY_BY_DATE' => 'Μηνιαία ανα ημέρομ.',
    'LBL_MORE_RECORDS_TXT'=>'Μόνο 1000 εγγραφές προβάλλονται. Χρησιμοποιείστε την εξαγωγή για να δείτε όλες τις εγγραφές',
	'LBL_MOVE_REPORT' => 'Μετακίνηση Αναφορών',
	'LBL_NEXT' => 'Επόμενο',
	'LBL_NEXT_TRIGGER_TIME' => 'Επόμενη ενεργοποίση ανοιχτή',
	'LBL_NO_OF_RECORDS' => 'Αριθμός Εγγραφών',
	'LBL_ON_THESE_DAYS' => 'Αυτές τις μέρες',
	'LBL_PRINT_REPORT' => 'Εκτύπωση αναφοράς',
	'LBL_RECORDS' => 'Εγγραφές',
	'LBL_REPORT_CSV' => 'Εξαγωγή CSV',
	'LBL_REPORT_DELETE_DENIED' => 'Άρνηση δικαιώματος διαγραφής της Αναφοράς',
	'LBL_REPORT_DETAILS' => 'Πληροφορίες Αναφοράς',
	'LBL_REPORT_EXPORT_EXCEL' => 'Εξαγωγή σε Excel',
	'LBL_REPORT_FOLDER' => 'Φάκελος Αναφοράς',
	'LBL_REPORT_NAME' => 'Όνομα Φακέλου',
	'LBL_REPORT_PRINT' => 'Εκτύπωση',
	'LBL_REPORTS' => 'Λίστα Αναφορών',
	'LBL_REPORTS_LIST' => 'Λίστα Αναφορών',
	'LBL_RUN_REPORT' =>'Εκτέλεση αναφοράς',
	'LBL_SAME_LEVEL_ROLES' => 'Ρόλοι ίδιου επιπέδου',
	'LBL_SCHEDULE_REPORTS' => 'Προγραμματισ. Αναφορών',
	'LBL_SELECT_COLUMNS' => 'Επιλέξτε Στήλες',
	'LBL_SELECTED_DATES' => 'Επιλεγμένς Ημερομ.',
	'LBL_SELECT_MONTH_AND_DAY' => 'Επιλογή Μήνα και Ημερομ.',
	'LBL_SELECT_RECIEPIENTS' => 'Επιλογή παραλητών',
	'LBL_SELECT_RELATED_MODULES' => 'Επιλέξτε Σχετικά Αρθρώματα',
	'LBL_SORT_ORDER' => 'Σειρά Ταξινόμησης',
	'LBL_SPECIFIC_DATE' => 'Σε συγκεκριμένη Ημερομ.',
	'LBL_SPECIFIC_EMAIL_ADDRESS' => 'Αποστολή σε συγκεκριμένο email',
	'LBL_SUBORDINATE_ROLES' => 'Δευτερεύοντες ρόλοι',
	'LBL_SUM' => 'Αθρ.',
	'LBL_SUM_VALUE' => 'Άθροισμα',
	'LBL_TOP' => 'Κορυφαία',
	'LBL_VIEW_DETAILS' => 'Εμφάνιση Λεπτομερειών',
	'LBL_WEEKLY' => 'Εβδομαδιαία',
	'LBL_WRITE_YOUR_DESCRIPTION_HERE' => 'Εισαγωγή Περιγραφής',
	'LBL_YEARLY' => 'Ετήσια',
	'Lead by Source'=>'Προοπτικές ανα Πηγή',
	'Lead Reports'=>'Αναφορές Προοπτικών',
	'Leads Email Report'=>'Αναφορά Email Προοπτικών',
	'Lead Status Report'=>'Αναφορά Κατάστασης Προοπτικών',
	'Open Quotes'=>'Ανοιχτές Προσφορές',
	'Open Tickets'=>'Ανοιχτά Δελτία Υποστ.',
	'Potential Pipeline'=>'Διαμεταγωγή Ευκαιριών', // Θέλει μελέτη η μετάφραση του Pipline
	'Potential Reports'=>'Αναφορές Ευκαιριών',
	'Potential that have Won'=>'Κερδισμένες Ευκαιρίες',
	'PRIMARY_MODULE' => 'Κυρίως Άρθρωμα',
	'Product Detailed Report'=>'Λεπτομερείς Αναφορά Προϊόντων',
	'Product Details'=>'Λεπτομέρειες Προϊόντων',
	'Product Reports'=>'Αναφορές Προϊόντων',
	'Products by Contacts'=>'Προϊόντα ανα Επαφές',
	'Products related to Contacts'=>'Προϊόντα σχετιζόμενα με Επαφές',
	'PurchaseOrder by Contacts'=>'Παραγγελίες Αγορών ανα Επαφή',
	'PurchaseOrder Detailed Report'=>'Λεπτομερείς Αναφορά Παραγγελιών Αγοράς',
	'PurchaseOrder related to Contacts'=>'Παραγγελίες Αγορών σχετιζόμενες με Επαφές',
	'PurchaseOrder Reports'=>'Αναφορές Παραγγελιών Αγοράς',
	'Quote Reports'=>'Αναφορές Προσφορών',
	'Quotes Detailed Report'=>'Λεπτομερείς Αναφορά Προσφορών',
	'Quotes that are Open'=>'Προσφορές που είναι ανοιχτές',
	'Report Name' => 'Όνομα Αναφοράς',
	'Reports'=>'Αναφορές',
	'SalesOrder Detailed Report'=>'Λεπτομερείς Αναφορά Παραγγελίας Πωλήσεων', //Added for SO
	'SalesOrder Reports'=>'Αναφορές Παραγγελιών Πωλήσεων', //Added for SO
	'SINGLE_Reports' => 'Αναφορά',
	'This Month Activities'=>'Δραστηριότητες Αυτού του Μήνα',
	'Tickets by Priority'=>'Δελτίων Υποστ. ανά Προτεραιότητα',
	'Tickets by Products'=>'Δελτίων Υποστ. ανά Προϊόντα',
	'Tickets related to Products'=>'Δελτίων Υποστ. σχετιζόμενα με Προϊόντα',
	'Tickets that are Open'=>'Δελτίων Υποστ. που είναι ανοιχτά',
	'Vendors Email Report'=>'Αναφορά Email Προμηθευτών',

	//charts labels
	'LBL_SELECT_CHART_TYPE' => 'Επιλέξτε τύπο χαρακτήρων',
	'LBL_CLICK_THROUGH_NOT_AVAILABLE' => 'Δεν μπορείτε να κάνετε κλίκ μέσα διότι έχετε επιλέξει περισσότερα από ένα αρθρώματα',
	'LBL_TOTAL_SUM_OF' => 'Συνολικό Αθροισ. %s',
	'LBL_AVG_OF' => 'Μέσος όρος %s',
	'LBL_MIN_OF' => 'Ελάχιστο %s',
	'LBL_MAX_OF' => 'Μέγιστο %s',
	'LBL_RECORD_COUNT' => 'Συν. Εγραφών',
	'LBL_PIE_CHART' => 'Κυκλικό διάγραμμα',
	'LBL_VERTICAL_BAR_CHART' => 'Κάθετη ραβδόγραμμα',
	'LBL_HORIZONTAL_BAR_CHART' => 'Οριζόντιο ραβδόγραμμα',
	'LBL_LINE_CHART' => 'Γραμμικό Γράφημα',
	'LBL_SELECT_CHART' => 'Επιλογή Διαγράμμ.',
	'LBL_CREATING_CHART_REPORT' => 'Δημιουργία Αναφοράς Διαγραμμ.',
	'LBL_EDITING_CHART_REPORT' => 'Επεξεργασία Αναφοράς Διαγράμμ.',
	'LBL_GENERATE_CHART' => 'Πραγωγή Διαγράμματος',
	'LBL_SELECT_GROUP_BY_FIELD' => 'Επιλογή Ομάδας ανα πεδίο',
	'LBL_SELECT_DATA_FIELD' => 'Επιλογή πεδίων δεδομένων',
	'LBL_MODIFY_CONDITION' => 'Τροποποίηση Συνθηκών',
	'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => 'Παρακαλώ επιλέξτε τουλάχιστον μια Ομάδα ανα πεδίο και ένα πεδίο δεδομένων.',
	'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => 'Για ραβδόγρ. και γραμμικό γράφημα, μπορείτε να επιλέξετε το μέγιστο 3 πεδία Δεδομένων.',
	'LBL_DETAIL_REPORT' => 'Λεπτομερείς Αναφορά',
	'LBL_PIVOT_REPORT' => 'Αναφορά σε πίνακα',
	'LBL_CHARTS' => 'Διαγράμματα',
    //Schedule Reports - Mail Content
    'LBL_AUTO_GENERATED_REPORT_EMAIL' => 'Αυτό είναι ένα μήνυμα ηλεκτρονικού ταχυδρομείου που δημιουργείται αυτόματα λόγο μιας προγραμματισμένης αναφοράς.',

);

$jsLanguageStrings = array(
	'JS_DUPLICATE_RECORD' => 'Δημιουργία Διπλότυπου Αναφοράς',
	'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => 'Περιορισμός: Τα στοιχεία των πεδίων γραμμής (Τιμοκατάλογος, Εκπτώσεις και Ποσότητα) μπορούν να χρησιμοποιηθούν μόνο όταν τα άλλα πεδία υπολογισμού δεν επιλέγονται.',
	'JS_NO_CHART_DATA_AVAILABLE' => 'Δεν είναι διαθέσιμα τα δεδομένα, παρακαλώ ελέγξτε τα επιλεγμένα πεδία',
);