<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * 
 * Greek Translation Project initiated : 13 February 2014
 * Repository : https://github.com/cerebrux/vtiger6-greek-translation
 * Author(s):
 *  -- Salih Emin (http://www.linkedin.com/in/salihemin)
 *  -- Mathias Stavrou (http://mstavrou.com/)
 *  -- Konstantinos Paraskeuopoulos (https://www.linkedin.com/in/kparaskevopoulos)
 *  -- Dimitris Anagnostou
 *  -- More: https://github.com/cerebrux/vtiger6-greek-translation/graphs/contributors
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => 'Προσθήκη Χρήστη',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  'Οι Προτιμήσεις Μου',
	'LBL_MORE_INFORMATION'  =>  'Περισσότερες Πληροφορίες',
	'LBL_USERLOGIN_ROLE'  =>  'Είσοδος χρήστη & Ρόλος',
	'LBL_USER_IMAGE_INFORMATION' => 'Φωτογραφία Χρήστη',
	'LBL_CURRENCY_CONFIGURATION' =>  'Διαμόρφωση Πεδίων Ισοτιμίας και Αριθμών',
	'LBL_ADDRESS_INFORMATION' => 'Διεύθυνση Χρήστη',
	'LBL_USER_ADV_OPTIONS' => 'Προχωρημένες Ρυθμίσεις Χρήστη',
	'Asterisk Configuration'  =>  'Διαμόρφωση Asterisk',
	'LBL_HOME_PAGE_COMPONENTS' => 'Στοιχεία Αρχικής Σελίδας',
	'LBL_TAG_CLOUD_DISPLAY' => 'Εμφάνιση Ετικετοσύννεφο',

	//MyPreference Fields
	'Role' => 'Ρόλος',
	'Admin' => 'Διαχειριστής',
	'User Name' => 'Όνομα Χρήστη',
	'Default Activity View' => 'Χρονική Εκκίνηση Ημερολογίου απο:',
	'Default Lead View' => 'Προεπιλεγμένη Προβολή Προοπτικής',
	'Title' => 'Τίτλος',
	'Office Phone' => 'Τηλέφωνο Γραφείου',
	'Department' => 'Τμήμα',
	'Reports To' => 'Αναφέρετε στον',
	'Yahoo id' => 'Yahoo id',
	'Home Phone' => 'Τηλ.Οικίας',
	'User Image' => 'Μεταφόρτωση Φωτογραφίας',
	'Date Format' => 'Μορφη Ημερομηνίας',
	'Tag Cloud' => 'Ετικετοσύννεφο',
	'Signature' => 'Υπογραφή',
	'Street Address' => 'Διεύθυνση',
	'Password' => 'Κωδικός',
	'Confirm Password' => 'Επιβεβαίωση Κωδικού',
	'LBL_SHOWN' => 'Εμφανής',
	'LBL_HIDDEN' => 'Κρυμμένα',
	'LBL_SHOW' => 'Εμφάνισε',
	'LBL_HIDE' => 'Κρύψε',
	'LBL_HOME_PAGE_COMPO' => 'Στοιχεία Αρχικής Σελίδας',
	'LBL_LOGIN_HISTORY' => 'Ιστορικό Σύνδεσης',
	'LBL_USERDETAIL_INFO' => 'Προβολή των στοιχείων του χρήστη',
	'LBL_DELETE_GROUP' => 'Διαγραφή Ομάδας',
	'LBL_DELETE_GROUPNAME' => 'Η Ομάδα που Πρόκειται να Διαγραφεί',
	'LBL_TRANSFER_GROUP' => 'Μεταφορά Ιδιοκτησίας σε/στον: ',
	'LBL_DELETE_USER' => 'Ο Χρήστης που Πρόκειται να Διαγραφεί',
	'LBL_TRANSFER_USER' => 'Μεταφορά Ιδιοκτησίας στον Χρήστη',
	'LBL_DELETE_PROFILE' => 'Διαγραφή Προφίλ',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'Μεταφορά Ρόλων στο Προφίλ',
	'LBL_PROFILE_TO_BE_DELETED' => 'Το Προφίλ που Πρόκειται να Διαγραφεί',
	'INTERNAL_MAIL_COMPOSER' => 'Εσωτερική Σύνθεση Ηλ. Μηνύματος',
	'Asterisk Extension'  =>  'Επέκταση Asterisk',
	' Receive Incoming Calls'  =>  'Λήψη εισερχόμενων κλήσεων',
	'Webservice Access Key' => 'Κλειδάριθμος Διαδικτυακής Υπηρεσίας',
	'Language' => 'Γλώσσα',
	'Theme' =>  'Εμφάνιση',
	'Time Zone'  =>  'Ζώνη Ώρας',
	'Decimal Separator'  =>  'Δεκαδικός Διαχωριστής',
	'Digit Grouping Pattern'  =>  'Πρότυπο Ομαδοποίησης Ψηφίου',
	'Digit Grouping Separator'  =>  'Διαχωριστικό Ομαδοποίησης Ψηφίου',
	'Symbol Placement'  =>  'Τοποθέτηση Συμβόλου',
	'Number Of Currency Decimals'  =>  'Αριθμός Δεκαδικών συναλλάγματος',
	'Truncate Trailing Zeros'  =>   'Περικόψτε μηδενικά',
	'Default Call Duration' => 'Προεπιλεγμένη Διάρκεια Κλήσεων (Λεπτά)',
	'Other Event Duration' => 'Διάρκεια Άλλων Γεγονότων (Λεπτά)',
	'Calendar Hour Format' => 'Μορφή Ώρας Ημερολογίου',
	'Tag Cloud' => 'Ετικετοσύννεφο',

	//Time zones-Dont change any value
    'Kwajalein'  =>  '(UTC-12:00) International Date Line West',
    'Pacific/Midway'  =>  '(UTC-11:00) Coordinated Universal Time-11',
    'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
    'Pacific/Honolulu'  =>  '(UTC-10:00) Hawaii',
    'America/Anchorage'  =>  '(UTC-09:00) Alaska',
    'America/Los_Angeles'  =>  '(UTC-08:00) Pacific Time (US &amp; Canada)',
    'America/Tijuana'  =>  '(UTC-08:00) Tijuana, Baja California',
    'America/Denver'  =>  '(UTC-07:00) Mountain Time (US &amp; Canada)',
    'America/Chihuahua'  =>  '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    'America/Mazatlan'  =>  '(UTC-07:00) Mazatlan',
    'America/Phoenix'  =>  '(UTC-07:00) Arizona',
    'America/Regina'  =>  '(UTC-06:00) Saskatchewan',
    'America/Tegucigalpa'  =>  '(UTC-06:00) Central America',
    'America/Chicago'  =>  '(UTC-06:00) Central Time (US &amp; Canada)',
    'America/Mexico_City'  =>  '(UTC-06:00) Mexico City',
    'America/Monterrey'  =>  '(UTC-06:00) Monterrey',
    'America/New_York'  =>  '(UTC-05:00) Eastern Time (US &amp; Canada)',
    'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Quito',
    'America/Lima'  =>  '(UTC-05:00) Lima',
    'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branco',
    'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (East)',
    'America/Caracas'  =>  '(UTC-04:30) Caracas',
    'America/Halifax'  =>  '(UTC-04:00) Atlantic Time (Canada)',
    'America/Manaus'  =>  '(UTC-04:00) Manaus',
    'America/Santiago'  =>  '(UTC-04:00) Santiago',
    'America/La_Paz'  =>  '(UTC-04:00) La Paz',
    'America/Cuiaba'  =>  '(UTC-04:00) Cuiaba',
    'America/Asuncion'  =>  '(UTC-04:00) Asuncion',
    'America/St_Johns'  =>  '(UTC-03:30) Newfoundland',
    'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Aires',
    'America/Sao_Paulo'  =>  '(UTC-03:00) Brasilia',
    'America/Godthab'  =>  '(UTC-03:00) Greenland',
    'America/Montevideo'  =>  '(UTC-03:00) Montevideo',
    'Atlantic/South_Georgia'  =>  '(UTC-02:00) Mid-Atlantic',
    'Atlantic/Azores'  =>  '(UTC-01:00) Azores',
    'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Cape Verde Is.',
    'Europe/London'  =>  '(UTC) London, Edinburgh, Dublin, Lisbon',
    'UTC'  =>  '(UTC) Coordinated Universal Time, Greenwich Mean Time',
    'Africa/Monrovia'  =>  '(UTC) Monrovia, Reykjavik',
    'Africa/Casablanca'  =>  '(UTC) Casablanca',
    'Europe/Belgrade'  =>  '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    'Europe/Brussels'  =>  '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    'Africa/Algiers'  =>  '(UTC+01:00) West Central Africa',
    'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    'Europe/Minsk'  =>  '(UTC+02:00) Minsk',
    'Africa/Cairo'  =>  '(UTC+02:00) Cairo',
    'Europe/Helsinki'  =>  '(UTC+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius',
    'Europe/Athens'  =>  '(UTC+02:00) Athens, Bucharest',
    'Europe/Istanbul'  =>  '(UTC+02:00) Istanbul',
    'Asia/Jerusalem'  =>  '(UTC+02:00) Jerusalem',
    'Asia/Amman'  =>  '(UTC+02:00) Amman',
    'Asia/Beirut'  =>  '(UTC+02:00) Beirut',
    'Africa/Windhoek'  =>  '(UTC+02:00) Windhoek',
    'Africa/Harare'  =>  '(UTC+02:00) Harare',
    'Asia/Kuwait'  =>  '(UTC+03:00) Kuwait, Riyadh',
    'Asia/Baghdad'  =>  '(UTC+03:00) Baghdad',
    'Africa/Nairobi'  =>  '(UTC+03:00) Nairobi',
    'Asia/Tehran'  =>  '(UTC+03:30) Tehran',
    'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisi',
    'Europe/Moscow'  =>  '(UTC+04:00) Moscow, Volgograd',
    'Asia/Muscat'  =>  '(UTC+04:00) Abu Dhabi, Muscat',
    'Asia/Baku'  =>  '(UTC+04:00) Baku',
    'Asia/Yerevan'  =>  '(UTC+04:00) Yerevan',
    'Asia/Karachi'  =>  '(UTC+05:00) Islamabad, Karachi',
    'Asia/Tashkent'  =>  '(UTC+05:00) Tashkent',
    'Asia/Kolkata'  =>  '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    'Asia/Colombo'  =>  '(UTC+05:30) Sri Jayawardenepura',
    'Asia/Katmandu'  =>  '(UTC+05:45) Kathmandu',
    'Asia/Dhaka'  =>  '(UTC+06:00) Dhaka',
    'Asia/Almaty'  =>  '(UTC+06:00) Almaty',
    'Asia/Yekaterinburg'  =>  '(UTC+06:00) Ekaterinburg',
    'Asia/Rangoon'  =>  '(UTC+06:30) Yangon (Rangoon)',
    'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirsk',
    'Asia/Bangkok'  =>  '(UTC+07:00) Bangkok, Jakarta',
    'Asia/Brunei'  =>  '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnoyarsk',
    'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulaan Bataar',
    'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kuala Lumpur, Singapore',
    'Asia/Taipei'  =>  '(UTC+08:00) Taipei',
    'Australia/Perth'  =>  '(UTC+08:00) Perth',
    'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutsk',
    'Asia/Seoul'  =>  '(UTC+09:00) Seoul',
    'Asia/Tokyo'  =>  '(UTC+09:00) Tokyo',
    'Australia/Darwin'  =>  '(UTC+09:30) Darwin',
    'Australia/Adelaide'  =>  '(UTC+09:30) Adelaide',
    'Australia/Canberra'  =>  '(UTC+10:00) Canberra, Melbourne, Sydney',
    'Australia/Brisbane'  =>  '(UTC+10:00) Brisbane',
    'Australia/Hobart'  =>  '(UTC+10:00) Hobart',
    'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostok',
    'Pacific/Guam'  =>  '(UTC+10:00) Guam, Port Moresby',
    'Asia/Yakutsk'  =>  '(UTC+10:00) Yakutsk',
    'Pacific/Fiji'  =>  '(UTC+12:00) Fiji',
    'Asia/Kamchatka'  =>  '(UTC+12:00) Kamchatka',
    'Pacific/Auckland'  =>  '(UTC+12:00) Auckland',
    'Asia/Magadan'  =>  '(UTC+12:00) Magadan',
    'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',

	'Summary' => 'Συνοπτική',
	'Detail' => 'Λεπτομέρης',
	'LBL_USER_LIST_DETAILS' => 'Λεπτομέρειες',
	
	'LBL_OLD_PASSWORD' => 'Παλίος Κωδικός',
	'LBL_CHANGE_PASSWORD' => 'Αλλαγή Κωδικού',
	'LBL_NEW_PASSWORD' => 'Νέος Κωδικός',
	'LBL_CONFIRM_PASSWORD' => 'Επιβεβαίωση Κωδικού',
	
	//Login strings
	'LBL_TO_CRM' => 'Σύνδεση στο Vtiger CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Μη Έγκυρο ΄Ονομα η Κωδικός Χρήστη.',
	'LBL_INVALID_USER_OR_EMAIL' => 'Μη Έγκυρο Όνομα Χρήστη η Ηλεκτρονική Διευθυνσή.',
	'LBL_EMAIL_SEND' => 'Σάς Έχουμε Αποστείλει Email για την Ανάκτηση του Κωδικόυ Πρόσβασης σας.',
	'ForgotPassword' => 'Ξεχάσατε τον Κωδικό σας',
	'LBL_CONNECT_WITH_US' => 'Επικοινωνήστε Μαζί μας',
	'LBL_GET_MORE' => 'Αποκτήστε περισσότερα από το Vtiger',
	
	'LBL_TRANSFER_RECORDS_TO_USER' => 'Μεταφορά εγγραφών στον Χρήστη',
	'LBL_USER_TO_BE_DELETED' => 'Ο Χρήστης Πρόκειται να Διαγραφεί',
);

$jsLanguageStrings = array(
	'JS_ENTER_OLD_PASSWORD'=>'Παρακαλώ Εισάγετε τον Παλίο σας Κωδικό Πρόσβασης.',
	'JS_ENTER_NEW_PASSWORD'=>'Παρακαλώ Πληκτρολογήστε τον Νέο σας Κωδικό Πρόσβασης.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Παρακαλώ Εισάγετε τον Κωδικό Επιβεβαίωσης.',
	'JS_REENTER_PASSWORDS'=>'Παρακαλω Ξανα Εισάγετε. Ο \"Νεός Κωδικός\" και \"Ο Κωδικός Επιβεβαίωση\" δεν Ταιριάζουν.',
	'JS_INVALID_PASSWORD'=>'Παρακαλω Καθορίστε ένα Έγκυρο Όνομα Χρήστη και Κωδικό.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Η Αλλαγή του Κωδικόυ Απέτυχε λόγο ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>'Αποτυχία. Ο Νέος Κωδικός Πρέπει να Εισαχθεί..',
	'JS_PASSWORD_INCORRECT_OLD'=>'Λανθασμένος Προηγούμενος Κωδικός. Εισάγετε Ξανά τον Κωδικό.',
);