<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * 
 * Greek Translation Project initiated : 13 February 2014
 * Repository : https://github.com/cerebrux/vtiger6-greek-translation
 * Author(s):
 *  -- Salih Emin (http://www.linkedin.com/in/salihemin)
 *  -- Mathias Stavrou (http://mstavrou.com/)
 *  -- Konstantinos Paraskeuopoulos (https://www.linkedin.com/in/kparaskevopoulos)
 *  -- Dimitris Anagnostou
 *  -- More: https://github.com/cerebrux/vtiger6-greek-translation/graphs/contributors
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'vtiger CRM',
	'POWEREDBY'=> 'Powered by vtiger CRM',
	'LBL_READ_LICENSE' => 'Read License',
	'LBL_PRIVACY_POLICY' => 'Privacy Policy',

	// Common Actions
	'LBL_SELECT_ALL' => 'Επιλογή όλων',
	'LBL_SELECT_TO_LOAD_LIST' => 'Επιλέξτε φόρτωμα Λίστας',
	'LBL_CREATING_NEW' => 'Δημιουργία Νέου',
	'LBL_EDITING' => 'Επεξεργασία',
	'LBL_SAVE' => 'Αποθήκευση',
	'LBL_CANCEL' => 'Άκυρωση',
	'LBL_BACK' => 'Πίσω',
	'LBL_IMPORT' => 'Εισαγωγή',
	'LBL_EXPORT' => 'Εξαγωγή',
	'LBL_FIND_DUPLICATES' => 'Βρείτε αντίγραφα',
	'LBL_MORE' => 'Περισσότερα',
	'LBL_ACTIONS' => 'Ενέργειες',
    'LBL_ADD' => 'Προσθέστε',
	'LBL_EDIT' => 'Επεξεργασία',
	'LBL_DELETE' => 'Διαγραφή',
	'LBL_SETTINGS'=> 'Settings',
	'LBL_ADD_COMMENT' => 'Αφήστε το σχολίο σας',
	'LBL_EDIT_FIELDS' => 'Eπεξεργασία πεδίων',
	'LBL_EDIT_WORKFLOWS' => 'Επεξεργασία ροής εργασιών',
	'LBL_EDIT_PICKLIST_VALUES' => 'Edit Picklist Values',
	'LBL_EDIT_MAILSCANNER' => 'Mail Converter',
	'LBL_RECORD_DELETE' => 'Το αρχείο που προσπαθείτε να δείτε έχει διαγραφεί',
	'LBL_RECORD_NOT_FOUND' =>'Το αρχείο που ψάχνετε δεν υπάρχει ',
	'LBL_EDIT_REASON' => 'Επεξεργαστείτε την αιτία',

	//'LBL_EDIT_CURRENT_FILTER' => 'Επεξεργασία φίλτρου',
	//'LBL_DELETE_CURRENT_FILTER' => 'Διαγραφη συγκεκριμένου Φίλτρου',
	'LBL_SELECT' => 'Επιλέξτε',
	'LBL_CLEAR' => 'Καθαρισμός',
	'LBL_YES' => 'Ναι',
	'LBL_NO' => 'Οχι',
	'LBL_SHOW_COMPLETE_DETAILS' => 'Πλήρες Λεπτομέρειες',
    'LBL_MASS_EDITING' => 'Μαζική Επεξεργασία',
	'LBL_DESELECT_ALL_RECORDS' => 'Διαγράψτε όλές τίς καταγραφές',
	'LBL_QUICK_CREATE' => 'Γρήγορη δημιουργία',
	'LBL_SEND_EMAIL' => 'Αποστολή Email',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'Ολόι οι λογαριασμόι Ηλεκτρονικού Ταχυδρομείου',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Παρακαλώ Επιλέξτε μία απο τίς παρακάτω επιλογές',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'Πηγένετε στήν πλήρες φόρμα',
	'LBL_SEND_SMS' => 'Αποστολη SMS',
	'LBL_FOUND' => 'Βρέθηκε',
	'LBL_CLICK_ADD' => 'Κλίκ Προσθήκη',
	'LBL_ADD_MORE_FIELDS' => 'Προσθέστε περισσότερα πεδία',
	'LBL_ADD_NOTE' => 'Προσθέστε Αρχείο',
	'LBL_CREATE_NEW' => 'Δημιουργία Νέου',
    'LBL_ADD_EVENT' => 'Προσθέστε γεγονός',
    'LBL_ADD_TASK' => 'Προσθέστε έργο/εργασία',
	'LBL_MARKETING_AND_SALES' => 'MARKETING και ΠΩΛΗΣΕΙΣ',
	'LBL_TOOLS_HEADER' => 'ΕΡΓΑΛΕΙΣ',
	'LBL_SUPPORT' => 'ΥΠΟΣΤΗΡΙΞΗ',
	'LBL_INVENTORY' => 'INVENTORY',
	'LBL_ANALYTICS' => 'ΑΝΑΛΥΤΙΚΑ ΣΤΟΙΧΕΙΑ',
	'LBL_HOME' => 'ΑΡΧΙΚΗ',

	// Common Link Labels
	'LBL_LAST_VIEWED_RECORDS' => 'Last Viewed Records',
	'LBL_DASHBOARD' => 'Πίνακας Γραφημάτων',
	'LBL_USER_SETTINGS' => 'Ρυθμίσεις Χρήστη',
	'LBL_MY_PREFERENCES' => 'Οί Ρυθμίσεις Μου',
	'LBL_SIGN_OUT' => 'Έξοδος',
	'LBL_HELP' => 'Βοήθεια',
	'LBL_DOCUMENTATION' => 'Documentation',
	'LBL_VIDEO_TUTORIAL' => 'Video Tutorial',
	'LBL_FEEDBACK' => 'Feedback',
	'LBL_CRM_SETTINGS' => 'Ρυθμίσεις Crm',
	'LBL_ON_DEMAND_ADMIN' => 'Προσθήκη/Διγραφή χρηστών',
	'LBL_ANNOUNCEMENT' => 'Ανακοίνωση',
	'LBL_CALENDAR' => 'Ημερολόγιο',
	'LBL_POST' => 'Δημοσίευση',
	'LBL_GUIDER' => 'Οδηγός',
	'LBL_DISPLAY_TYPE' => 'Τύπος Οθόνης',
	'LBL_DISPLAY_WIDETYPE' => 'Ευρία',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Μεσαία',
	'LBL_DISPLAY_NARROWTYPE' => 'Στενής',
	'LBL_TAG_THIS_RECORD' => 'Καρφιτσώστε αυτή την εγγραφή',
	'LBL_PAGE' => 'Σελίδα',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Προσπεράστε σελίδα',
	'LBL_PROFILE_PASSWORD' => 'Προφίλ / Κωδικός',

	// Common Fields
	'LBL_USER' => 'Χρήστης',
	'LBL_GROUP' => 'Ομάδες',
	'Last Modified By' => 'Τελευταία τροποποίηση απο',
	'Created Time' => 'Δημιουργήθηκε στίς',
	'Modified Time' => 'Τροποποιήθηκε στίς',
	'Description' => 'Περιγραφή',
	'Assigned To'=>'Ανατέθηκε σε/στον',

	//Loading Labels
	'LBL_LOADING' => 'Φορτώση',
	'LBL_LOADING_WIDGET' => 'Φόρτωση Widget',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'Γίνετε Φόρτωση Παρακαλώ Περιμένετε',

	// Detail View
	'LBL_UPDATES' => 'Ενημερώσεις',
	'LBL_SHOW_FULL_DETAILS' => 'Πλήρες Λεπτομέρειες',
	'LBL_SUMMARY_DETAILS' => 'Περιληπτικα Στοιχεία',
	'LBL_ADD_NEW_COMMENT' =>'Προσθήκη Νέου Σχόλιου',
	'LBL_NO_UPDATES' => 'Καμμία Ενημέρωση',
	'LBL_ACTIVITIES' => 'Δραστηριότητες',
	'LBL_NO_PENDING_ACTIVITIES' => 'Καμμία εκκρεμής δραστηριότητα',
	'LBL_SUMMARY' => 'Περίληψη',
	'LBL_DETAILS' => 'Λεπτομέρειες',

	// Popup window
	'LBL_SEARCH_FOR' => 'Αναζήτηση για',
	'LBL_IN' => 'μέσα',
	'LBL_TYPE_SEARCH' => 'Πληκτρολογήστε για Αναζήτηση',
	'LBL_SEARCH_BUTTON' => 'Κομβίον Αναζήτησης',
	'LBL_ADVANCE_SEARCH' => 'Σύνθετη',
	'LBL_LOADING_PLEASE_WAIT' => 'Φορτώνει...Παρακαλώ Περιμένετε',
	'LBL_PLEASE_SELECT_MODULE' => 'Παρακαλώ Επιλέξτε ένα module',

	//DropDown Category
	'LBL_USERS' => 'Χρήστες',
	'LBL_GROUPS' => 'Γκρούπς',

	//EditView Form Links
	'LBL_FULL_FORM' => 'Πλήρης Φόρμα',
	'LBL_SIMPLE_FORM' => 'Απλή Φόρμα',

	//Recent Comments
	'LBL_ADD_YOUR_COMMENT_HERE' => 'Αφήστε Το Σχόλιο σας εδώ....',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Λόγος τροποποίησης σχόλιου',
	'LBL_REPLY' => 'Απάντηση',
	'LBL_VIEW_THREAD' => 'Δείτε ',
	'LBL_NO_COMMENTS' => 'Κανένα Σχόλιο',
	'LBL_REPLIES' => 'Απαντήσεις',

	//Translation for all modules
	'Accounts' => 'Οργανισμοί',
	'Assets' => 'Περιουσιακά Στοιχεία',
	'Calendar' => 'Ημερολόγιο',
	'Campaigns' => 'Καμπάνίες',
	'Contacts' => 'Επαφές',
	'Documents' => 'Έγγραφα',
	'Leads' => 'Leads',
	'ModComments' => 'Σχόλια',
	'Potentials' => 'Ευκαιρίες',
	'PriceBooks' => 'Τιμοκατάλογοι',
	'Products' => 'Προιόντα',
	'Project' => 'Projects',
	'ProjectMilestone' => 'Καμπύλη διαχείρησης έργου',
	'ProjectTask' => 'Αναθετημένες εργασίες για τήν διαχείρηση του έργου',
	'ServiceContracts' => 'Συμβόλαια Υπηρεσιών',
	'Services' => 'Υπηρεσίες',
	'Vendors' => 'Πωλητές',
	'Rss' => 'RSS',
	'Quotes'=>'Προσφορές',
	'PurchaseOrder'=>'Εντολή Αγοράς',
	'SalesOrder'=>'Εντολή Πώλησης',
	'Invoice'=>'Τιμολόγιο',
	'MailManager' => 'Διαχείρηση Ταχυδρομείου',
	'Activities' => 'Δραστηριότητες',


	//Basic String Translation
	'LBL_ADD_RECORD' => 'Προσθήκη Καταγραφής',
	'LBL_RECENTLY_MODIFIED' => 'Τελευταία Τροποποίηση',
	'LBL_RECORDS_LIST' => 'Λίστα Καταγραφών',
	'LBL_RECORD_SUMMARY' => 'Module Summary',
	'LBL_RECORD_SUMMARY' => 'Module Details',
	'LBL_ACCESS_DENIED_FOR' => 'Η Πρόσβαση δεν είναι εφικτή',
	'LBL_GO_BACK' => 'Πηγαίνετε Πίσω',
	'LBL_NO_DATA_AVAILABLE' => 'Κανένα δεδομένο δεν είναι διαθέσιμο',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'Πληκτρολογήστε μία Λέξη κλειδί και πατήστε enter',
	'LBL_ALL_RECORDS' => 'Όλες οι Καταγραφές',
	'LBL_NO_RECORDS_FOUND' => 'Δέν Βρέθηκε καμμία Καταγραφή',

	//Filters & Advance Filter
	'LBL_AND' => 'και',
	'LBL_OR' => 'ή',
	'LBL_NONE' => 'κανένα',
	'LBL_APPROVE' => 'Αποδοχή',
	'LBL_DENY' => 'Άρνηση',
	'LBL_EQUALS' => 'ίσα',
	'LBL_NOT_EQUAL_TO' => 'not equal to',
	'LBL_STARTS_WITH' => 'Ξεκινάει με',
	'LBL_ENDS_WITH' => 'Τελειώνει με',
	'LBL_CONTAINS' => 'Περιέχει',
	'LBL_DOES_NOT_CONTAIN' => 'Δέν περιέχει',
	'LBL_LESS_THAN' => 'Λιγότερο Από',
	'LBL_GREATER_THAN' => 'Περισσότερο Από',
	'LBL_LESS_THAN_OR_EQUAL' => 'Λιγότερο ή Ίσο',
	'LBL_GREATER_OR_EQUAL' => 'Μεγαλύτερο ή Ίσο',
	'LBL_BEFORE' => 'πρίν',
	'LBL_AFTER' => 'Μετά',
	'LBL_BETWEEN' => 'Μεταξύ',
	'LBL_SEARCH' => 'Αναζήτηση',
	'LBL_SEARCH_IN' => 'Αναζήτηση σε',
	'LBL_ADD_CONDITION' => 'Προσθήκη προϋπόθεσεων',
	'LBL_ADD_GROUP' => 'Προσθήκη πολλαπλών προϋπόθεσεων',
	'LBL_FILTER_CONDITIONS' => 'Φίλτρα προϋπόθεσεων',
	'LBL_ALL_CONDITIONS' => 'Όλες οι προϋπόθεσεις',
	'LBL_ALL_CONDITIONS_DESC' => 'Όλες οι προϋπόθεσεις πρέπει να περιέχουν',
	'LBL_ANY_CONDITIONS' => 'Οποιαδήποτε προϋπόθεση',
	'LBL_ANY_CONDITIONS_DESC' => 'Τουλάχιστον Μία προϋπόθεση πρέπει να τηρήτε',
	'LBL_SELECT_FIELD' => 'Επιλέξτε Πεδίο',
	'LBL_SELECT_MODULE' => 'Select Module',
	'LBL_CREATE_NEW_FILTER' => 'Δημιουργία Νέου Φίλτρου',
	'All' => 'Όλα',
	'Others' => 'Λοιπά',
	'Pending' => 'Εκκρεμούν',
	'Public' => 'Δημόσια',

	//Advance Search
	'LBL_SAVE_FILTER' => 'Αποθήκευση Φίλτρου',
	'LBL_SAVE_MODIFY_FILTER' => 'Αποθήκευση Τροποποιημένου Φίλτρου',
	'LBL_SEARCH_RESULTS' => 'Αποτελέσματα Αναζητήσεως',
	'LBL_SAVE_AS_FILTER' => 'Αποθήκευση ώς Φίλτρο',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Άρνηση Πρόσβασης',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'Λεπτομέρεις Αντικειμένου',
	'LBL_CURRENCY' => 'Ισοτιμία',
	'LBL_TAX_MODE' => 'Tax Mode',
	'LBL_INDIVIDUAL' => 'Κλίμακα Φορολογίας',
	'LBL_GROUP' => 'Ομάδα',
	'LBL_TOOLS' => 'Εργαλεία',
	'LBL_ITEM_NAME' => 'Όνομα Αντικειμένου',
	'LBL_QTY_IN_STOCK' => 'Απόθεμα',
	'LBL_QTY' => 'Ποσότητα',
	'LBL_LIST_PRICE' => 'Λίστα Τιμών',
	'LBL_TOTAL' => 'Σύνολο',
	'LBL_NET_PRICE' => 'Καθαρή Αξία',
	'LBL_DISCOUNT' => 'Έκπτωση',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Σύνολο Μετά τήν Έκπτωση',
	'LBL_TAX' => 'Φόρος',
	'LBL_ADD_PRODUCT' => 'Προσθήκη προϊόντος',
	'LBL_ADD_SERVICE' => 'Προσθήκη Υπηρεσίας',
	'LBL_ITEMS_TOTAL' => 'Σύνολο Αντικειμένων',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Έξοδα Αποστολής και μεταφοράς',
	'LBL_PRE_TAX_TOTAL' => 'Σύνολο προ Φόρου',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Φόρος αποστολής και μεταφοράς',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Set S&H Taxes For',
	'LBL_ADJUSTMENT' => 'Προσαρμογή',
	'LBL_DEDUCT' => 'Συμπέρασμα',
	'LBL_GRAND_TOTAL' => 'Ολικό Σύνολο',
	'LBL_ZERO_DISCOUNT' => 'Μηδενική Έκπτωση',
	'LBL_OF_PRICE' => 'Τιμή',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Απευθείας Μείωση Τιμής',
	'LBL_SET_DISCOUNT_FOR' => 'Ορίστε Έκπτωση για',
	'LBL_STOCK_NOT_ENOUGH' => 'Μη Επαρκές Απόθεμα',
	'LBL_MAX_QTY_SELECT' => 'Η Μέγιστη Τιμή είναι',
	'LBL_DRAG' => 'Σύρτε',
	'LBL_TOTAL_TAX_AMOUNT' => 'Συνολική Μέγιστη Ποσότητα',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Απευθείας Ποσό Έκπτωσης',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Τελικό Ποσό Έκπτωσης',
	'LBL_MORE_CURRENCIES' => 'Περισσότερες Ισοτιμίες',
	'LBL_SET_TAX_FOR' => 'Ορισμός Φόρου Για',
	'LBL_GROUP_TAX' => 'Ομάδα Φόρων',
	'LBL_BILLING_ADDRESS_FROM' => 'Αντιγραφή Διεύθυνσης Πληρωμής Από',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Αντιγραφή Διεύθυνσης Αποστολής Από',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Διεύθυνση Αποστολής',
	'LBL_COPY_BILLING_ADDRESS' => 'Διεύθυνση Πληρωμής',

	//DetailView Actions
	'LBL_CREATE' => 'Δημιουργία',
	'LBL_GENERATE' => 'Δημιουργία',
    'LBL_DUPLICATE' => 'Αντίγραφο',
	'Add Note' => 'Προσθήκη Εγγράφου',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Προσθήκη Widget',
	'LBL_COMMENTS' => 'Σχόλια',
	'LBL_REFRESH' => 'Ανανέωση',
	'LBL_CLOSE' => 'Κλείσιμο',
	'LBL_ALL' => 'Όλα',
	'LBL_UPDATED' => 'Ανανεωμένα',
	'LBL_FROM' => 'Από',
	'LBL_TO' => 'Πρός',
	'LBL_to' => 'Πρός',
	'LBL_ON' => 'on',
	'LBL_OF' => 'από',
	'LBL_BY' => 'by',
	'LBL_ADDED' => 'Προστέθηκε',
	'LBL_FOR' => 'for',
	'LBL_CREATED' => 'Δημιουργήθηκε',
	'LBL_DELETED' => 'Διαγράφτηκε',
	'LBL_RESTORED' => 'Επαναφέρθηκε',
	'LBL_COMMENTED' => 'Σχολιάστηκε',
	'LBL_REMOVED' => 'Αφαιρέθηκε',
	'LBL_REMOVE' => 'Αφαίρεση',
	'LBL_AT' => 'στο',
	'LBL_MINE' => 'Δικό Μου',
	'History' => 'Ιστορικό',
	'Upcoming Tasks' => 'Επερχόμενες Εργασίες',
	'LBL_YEAR' => 'Έτος',
	'LBL_YEARS' => 'Έτοι',
	'LBL_MONTH' => 'Μήνας',
	'LBL_MONTHS' => 'Μήνες',
	'LBL_DAY' => 'Ημέρα',
	'LBL_DAYS' => 'Ημέρες',
	'LBL_HOUR' => 'Ώρα',
	'LBL_HOURS' => 'Ώρες',
	'LBL_MINUTE' => 'Λεπτό',
	'LBL_MINUTES' => 'Λεπτά',
	'LBL_SECOND' => 'Δευτερόλεπτο',
	'LBL_SECONDS' => 'Δευτερόλεπτα',
	'LBL_JUSTNOW' => 'Μόλις Τώρα',
	'LBL_CUSTOM_INFORMATION' => 'Custom Information',
	'LBL_NO_RECENT_UPDATES' => 'Καμμία Πρόσφατη Ενημέρωση',
	'LBL_NO_DATA' => 'Κανένα Δεδομένο',
	'LBL_PERMISSION_DENIED' => 'Άρνηση Έγκρισης',
	'LBL_HANDLER_NOT_FOUND' => 'Ο Διαχειριστής Δέν Βρέθηκε',
	'LBL_FILTER' => 'Φίλτρο',
	'LBL_DUE' => 'Μέσα σε',
	'LBL_DAYS' => 'Ημέρες',
	'LBL_COMPLETED' => 'Ολοκληρώθηκαν',
	'LBL_AGO' => 'Πρίν Από',
	'LBL_CHANGED' => 'Αλλάχθηκαν',
	'Single_Users' => 'Χρληστης',
	'LBL_MATCHED_THIS_CRITERIA'=> 'Ταιριάζουν με τα Κριτήρια',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'Καμμία Προγραμματισμένη Δραστηριότητα',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'Καμμία Εκπρόθεσμη Δραστηριότητα',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'Καμμία Ανανέωση Η Σχόλια',
	'LBL_MINI_LIST' => 'Mini Λίστα',
	'LBL_NOTEPAD' => 'Σημειωματάριο',
	'LBL_NOTEPAD_NAME' => 'Όνομα Σημειωματάριου',
	'LBL_NOTEPAD_CONTENT' => 'Περιεχόμενο Σημειωματάριου',
	'LBL_LAST_SAVED_ON' => 'Τελευταία Αποθήκευση στο',
	'Mini List' => 'Mini Λίστα',
	'Notebook' => 'Σημειωματάριο',
	'LBL_RESULT_FOR_THE_TAG' => 'Αποτέλεσμα για τήν Ετικέτα',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'Δείτε το Όνομα',
	'LBL_CREATE_VIEW' => 'Creating new View',
	'LBL_BASIC_DETAILS' => 'Βασικές Πληροφορίες',
	'LBL_CHOOSE_COLUMNS' => 'Διαλέξτε Σειρά και Στήλες',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Max 12',
	'LBL_FILTER_ON_DATE' => 'Φιλτράρισμα Ημερομηνίας',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Choose filter Conditions',
	'LBL_ADD_CONDITION' => 'Προσθήκη Συνθήκης',
	'LBL_SET_AS_DEFAULT' => 'Ορισμός ως Προεπιλογή',
	'LBL_LIST_IN_METRICS' => 'List in Metrics',
	'LBL_SET_AS_PUBLIC' => ' Ορισμός ώς Δημόσιο',
	'LBL_AND' => 'Και',
	'LBL_OR' => 'ή',
	'LBL_ADD_MORE_COLUMNS' => 'Προσθήκη Περισσότερων Στήλων',
	'LBL_ADD_GROUP' => 'Προσθήκη Ομάδος',


	//DateFilter Conditions
	'LBL_CUSTOM' => 'Custom',
	'LBL_PREVIOUS_FY' => 'Προηγούμενο FY',
	'LBL_CURRENT_FY' => 'Τρέχων FY',
	'LBL_NEXT_FY' => 'Επόμενο FY',
	'LBL_PREVIOUS_FQ' => 'Προηγούμενο FQ',
	'LBL_CURRENT_FQ' => 'Τρέχων FQ',
	'LBL_NEXT_FQ' => 'Επόμενο FQ',
	'LBL_YESTERDAY' => 'Χθές',
	'LBL_TODAY' => 'Σήμερα',
	'LBL_TOMORROW' => 'Αύριο',
	'LBL_LAST_WEEK' => 'Προηγούμενη Εβδομάδα',
	'LBL_CURRENT_WEEK' => 'Τρέχων Εβδομάδα',
	'LBL_NEXT_WEEK' => 'Επόμενη Εβδομάδα',
	'LBL_LAST_MONTH' => 'Προηγούμενος Μήνας',
	'LBL_CURRENT_MONTH' => 'Τρέχων Μήνας',
	'LBL_NEXT_MONTH' => 'Επόμενος Μήνας',
	'LBL_LAST_7_DAYS' => 'Τελευταίες 7 ημέρες',
	'LBL_LAST_30_DAYS' => 'Τελευταίες 30 ημέρες',
	'LBL_LAST_60_DAYS' => 'Τελευταίες 60 ημέρες',
	'LBL_LAST_90_DAYS' => 'Τελευταίες 90 ημέρες',
	'LBL_LAST_120_DAYS' => 'Τελευταίες 120 ημέρες',
	'LBL_NEXT_30_DAYS' => 'Επόμενες 30 ημέρες',
	'LBL_NEXT_60_DAYS' => 'Επόμενες 60 ημέρες',
	'LBL_NEXT_90_DAYS' => 'Επόμενες 90 ημέρες',
	'LBL_NEXT_120_DAYS' => 'Επόμενες 120 ημέρες',

	//advanced Filter Options
	'LBL_NONE' => 'Κανένα',
	'LBL_EQUALS' => ';ίσος',
	'LBL_NOT_EQUAL_TO' => 'Δέν είναι ίσο με',
	'LBL_STARTS_WITH' => 'Ξεκινάει με',
	'LBL_ENDS_WITH' => 'Τελειώνει με',
	'LBL_CONTAINS' => 'Περιέχει',
	'LBL_DOES_NOT_CONTAIN' => 'Δεν Περιέχει',
	'LBL_LESS_THAN' => 'Λιγότερο από',
	'LBL_GREATER_THAN' => 'Μεγαλύτερο από',
	'LBL_LESS_THAN_OR_EQUAL' => 'Λιγότερο ή ίσο',
	'LBL_GREATER_OR_EQUAL' => 'Μεγαλύτερο ή ίσο',
	'LBL_BEFORE' => 'Πρίν',
	'LBL_AFTER' => 'Μετά',
	'LBL_BETWEEN' => 'Μεταξύ',
	'LBL_IS_EMPTY'=> 'Κενό',

	//Detail view summary widgets
	'LBL_OWNER' => 'Ιδιοκτήτης',
	'LBL_CREATED_ON' => 'Δημιουργήθηκε στίς',
	'LBL_MODIFIED_ON' => 'Τροποποιήθηκε στίς',
	'LBL_MODIFIED' => 'Τροποποιήθηκε',
	'LBL_COMMENTED' => 'Σχολιάστηκε',

    //calender set-reminder
    'LBL_BEFORE_EVENT' => ' Πρίν από το Γεγονός',

	//Dashboard widgets
	'History' => 'Ιστορικό',
	'Upcoming Activities' => 'Προσεχής Δραστηριότητες',
	'Overdue Activities' => 'Εκπρόθεσμες Δραστηριότητες',
	'Funnel' => 'Χωνί',
	'Potentials by Stage' => 'Ευκαρίες Ανά Επίπεδο',
	'Pipelined Amount' => 'Sales Pipeline',
	'Total Revenue' => 'Συνολικά Έσοδα',
	'Top Potentials' => 'Κορυφαίες Ευκαιρίες',
	'Forecast' => 'Πρόγνωση',
	'Leads Created' => 'Leads Created',
	'Leads by Status' => 'Συστάσεις ανά Κατάσταση',
	'Leads by Source' => 'Πηγές Συστάσεων',
	'Leads by Industry' => 'Συστάσεις ανά Κλάδο',
	'Tickets by Status' => 'Tickets by Status',
	'Open Tickets' => 'Open Tickets',
	'Funnel Amount' => 'Συνολικό Ποσό ανα Επίπεδο Πωλήσεων',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'Εξαγωγή Όλων τών Δεδομένων',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Εξαγωγή Δεδομένων σε Αυτή την Σελίδα',
	'LBL_EXPORT_SELECTED_RECORDS' => 'Εξαγωγή των Επιλεγμένων Καταγραφών',
	'LBL_EXPORT_RECORDS' => 'Εξαγωγή Καταγραφών',
	'LBL_NO_RECORD_SELECTED' => 'Καμμία Καταγραφή Δέν έχει Επιλεχθεί',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove default widget',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'Αυτό το Φίλτρο Υπάρχει Ήδη',

	'LBL_ADD_MANAGE_MODULES' => 'Προσθήκη / Διαχείρηση Modules',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Εξατομίκευση του Μενού',

	// Added Common Keys for all modules
	'Account Name' => 'Ονομά Οργανισμού',
	'Add Comment' => 'Προσθήκη Σχόλιου',
	'Adjustment' => 'Προσαρμογή',
	'Annual Revenue' => 'Ετήσια Έσοδα',
	'Apparel'=>'Εμφάνιση',
	'Banking'=>'Τραπεζικός',
	'Billing Address' => 'Διεύθυνση Πληρωμής ',
	'Billing City' => 'Πόλη Πληρωμής',
	'Billing Code' => 'Ταχ.Κώδικας Πληρωμής',
	'Billing Country' => 'Χώρα Πληρωμής',
	'Billing Po Box' => 'Billing PO Box',
	'Billing State' => 'Πολιτεία Πληρωμής',
	'Biotechnology'=>'Βιοτεχνολογία',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Μεταφορέας',
	'Category'=>'Κατηγορία',
	'Chemicals'=>'Χημικά',
	'City' => 'Πόλη',

	'Cold Call'=>'Τηλεφωνική Επαφή',
	'Existing Customer'=>'Υπάρχων Πελάτης',
	'Self Generated'=>'Αυτοδημιούργητος',
	'Employee'=>'Υπάλληλος',
	'Partner'=>'Συνέταιρος',
	'Public Relations'=>'Δημόσιες Σχέσεις',
	'Direct Mail'=>'Απευθείας Μήνυμα Ηλ.Ταχυδρομείου',
	'Conference'=>'Συνεδρίαση',
	'Trade Show'=>'Εμπορική Επίδειξη',
	'Web Site'=>'Ιστοσελίδα',
	'Word of mouth'=>'Απο Στόμα σε Στόμα',
	'Other'=>'Αλλό',

	//for leads and accounts
	'--None--'=>'--Κανένα--',
	'Acquired'=>'Επίκτητος',
	'Active'=>'Ενεργό',
	'Market Failed'=>'Αποτυχία Αγοράς',
	'Project Cancelled'=>'Το Έργο Ματαιώθηκε',
	'Shutdown'=>'Κλείσιμο',
	'Apparel'=>'Εμφάνιση',
	'Banking'=>'Τραπεζικός',
	'Biotechnology'=>'Βιοτεχνολογία',
	'Chemicals'=>'Χημικά',
	'Communications'=>'Επικοινωνίες',
	'Construction'=>'Κατασκευές',
	'Consulting'=>'Συμβουλευτική',
	'Education'=>'Εκπαίδευση',
	'Electronics'=>'Ηλεκτρονικά',
	'Energy'=>'Ενέργεια',
	'Engineering'=>'Μηχανική',
	'Entertainment'=>'Διασκέδαση',
	'Environmental'=>'Περιβαντολογική',
	'Finance'=>'Οικονομική',
	'Food & Beverage'=>'Φαγητό και Αναψυκτικά',
	'Government'=>'Κυβερνητική',
	'Healthcare'=>'Υγεία',
	'Hospitality'=>'Φιλοξενία',
	'Insurance'=>'Ασφάλιση',
	'Machinery'=>'Μηχανήματ',
	'Manufacturing'=>'Βιομηχανία',
	'Media'=>'Μ.Μ.Ε',
	'Not For Profit'=>'Μη Κερδοσκοπική',
	'Recreation'=>'Μεταποίησης',
	'Retail'=>'Λιανικής',
	'Shipping'=>'Ναυτιλιακή',
	'Technology'=>'Τεχνολογίας',
	'Telecommunications'=>'Επικοινωνιών',
	'Transportation'=>'Μεταφορών',
	'Utilities'=>'Παροχών',

	'Contact Name' => 'Όνομα Επαφής',
	'Conversion Rate' => 'Conversion Rate',

	'Shipping Address' => 'Διεύθυνση Αποστολής',
	'Shipping City' => 'Πόλη Αποστολής',
	'Shipping State' => 'Πολιτεία Αποστολής',
	'Shipping Code' => 'Κωιδικός Αποστολής',
	'Shipping Country' => 'Χώρα Αποστολής',
	'Shipping Po Box' => 'Ταχυδρομικός Κωδικας',
	'Country' => 'Χώρα',
	'Description' => 'Περιγραφή',

	'Created'=>'Δημιουργήθηκε',
	'Approved'=>'Εγκρίθηκε',
	'Delivered'=>'Παραδόθηκε',
	'Cancelled'=>'Ακυρώθηκε',

	'Currency' => 'Ισοτιμία',
	'LBL_BASE_CURRENCY' => 'Βασική Ισοτιμία',

	'Discount Percent' => 'Ποσοστό Έκπτωσης Επι τής %',
	'Discount Amount' => 'Ποσότητα Έκπτωσης',
	'Item Discount Amount' => 'Ποσότητα Έκπτωσης Αντικειμένου',
	'Item Discount Percent' => 'Ποσοστό Έκπτωσης Αντικειμένου',

	'Due Date' => 'Προθεσμία',
	'Due Date & Time' => 'Ημερομηνία Προθεσμίας',
	'Email' => 'Πρωτεύον Email',
	'Secondary Email' => 'Δευτερεύον Email',
	'Other Email' => 'Αλλο Email',
	'Email Opt Out' => 'Email Opt Out',

	'Expected Close Date' => 'Αναμενόμενη Ημερομηνία Περάτωσης',

	'Fax' => 'Fax',

	'Last Name' => 'Επίθετο',
	'First Name' => 'Όνομα',

	'High' => 'Υψηλό',
	'Low' => 'Χαμηλό',

	'In Progress' => 'Σε Εξέλιξη',


	'Subject' => 'Θέμα',
	'Shipping Address'=>'Διεύθυνση Αποστολής',
	'Shipping Po Box'=>'Ταχ.Κώδικας',
	'Shipping City'=>'Πόλη Αποστολης',
	'Shipping State'=>'Νομός Αποστολής',
	'Shipping Code'=>'Κωδικός Αποστολής',
	'Shipping Country'=>'Χώρα Αποστολής',
	'Terms & Conditions' => 'Όροι Και Προϋποθέσεις',
	'Item Name' => 'Ονοασία Αντικειμένου',
	'Quantity' => 'Ποσότητα',
	'List Price' => 'Λίστα Τιμών',
	'Item Comment' => 'Σχολιασμός Αντικειμένου',
	'Tax1' => 'Φόρος1',
	'Tax2' => 'Φόρος2',
	'Tax3' => 'Φόρος3',
	'Excise Duty' => 'Φόρος Κατανάλωσης',
	'Total' => 'Σύνολο',
	'Sub Total' => 'Υποσύνολο',
	'Tax Type' => 'Τύπος Φορολογίας',
	'S&H Amount' => 'S&H Amount',
	'Status' => 'Κατάσταση',
	'Vendor Name'=>'Όνομα Προμηθευτή',

	'LBL_ADDRESS_INFORMATION' => 'Πληροφοριίες Διεύθυνσης',
	'LBL_DESCRIPTION_INFORMATION' => 'Πληροφορίες Περιγραφής',
	'LBL_TERMS_INFORMATION' => 'Όροι και Προϋποθεσεις',
	'LBL_PRICING_INFORMATION' => 'Πληροφορίες Τιμής',
	'LBL_RELATED_PRODUCTS' => 'Σχετικά Προϊοντα',
	'LBL_REMINDER_INFORMATION' => 'Πληροφορίες Υπενθύμισης',

	'LBL_FOLDER_SAVED' => 'Ο Φάκελος Αποθηκεύτηκε',
	'LBL_FOLDER_EXISTS' => 'Ο Φάκελος Υπάρχει ήδη',
	'LBL_FOLDER_DELETED' => 'Ο Φάκελος Διαγράφτηκε',

	'Lead Source' => 'Πηγή Συστάσεων',
	'Mobile' => 'Κινητό Τηλέφωνο',

	'Notify Owner' => 'Υπενθύμιση Διαχειρηστή',
	'Other Phone' => 'Δευτερεύον Τηλ',
	'Phone' => 'Πρωτεύον Τηλ',

	'State' =>  'Νομός',
	'Po Box' => 'Τ.Κ',
	'Postal Code' => 'Ταχυδρομικός Κώδικας',

	'Potential Name' => 'Όνομα Ευκαιρίας',
	'Priority'=>'Προτεραιότητα',

	'Product Name' => 'Όνομα Προϊόντος',
	'Rating' => 'Κατάταξη',

	'Related To'=>'Σχετίζετε με',
	'Type' => 'Τύπος',

	'Reviewed'=>'Ελέγχθηκε',
	'Salutation' => 'Προσφώνηση',
	'Street' => 'Οδός',
	'Support Start Date' => 'Ημερομηνία Έναρξης Υποστήριξης',
	'Support Expiry Date' => 'Ημερομηνία Λήξης Υποστήριξης',
	'Sales Start Date'=>'Ημ.Έναρξης Πώλησης',
	'Sales End Date'=>'Ημ.Λήξης Πώλησης',

	//Dashboard list of widgets translation
	'Open Tickets' => 'Ανοιχτά Εισητήρια',
	'LBL_SELECT_STATUS' => 'Επιλέξτε Κατάσταση',
	'LBL_BLANK' => '-Κενό-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM honest Open Source',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Οργανισμός',
	'SINGLE_Contacts' => 'Επαφές',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Κυρ',
	'LBL_Mon' => 'Δευ',
	'LBL_Tue' => 'Τρι',
	'LBL_Wed' => 'Τετ',
	'LBL_Thu' => 'Πεμ',
	'LBL_Fri' => 'Παρ',
	'LBL_Sat' => 'Σαβ',

	//Months in 3 letters translations
	'LBL_Jan' => 'Ιαν',
	'LBL_Feb' => 'Φεβ',
	'LBL_Mar' => 'Μαρ',
	'LBL_Apr' => 'Απρ',
	'LBL_May' => 'Μαι',
	'LBL_Jun' => 'Ιου',
	'LBL_Jul' => 'Ιου',
	'LBL_Aug' => 'Αυγ',
	'LBL_Sep' => 'Σεπ',
	'LBL_Oct' => 'Οκτ',
	'LBL_Nov' => 'Νοε',
	'LBL_Dec' => 'Δεκ',

	'LBL_CALENDAR_SETTINGS' => 'Ρυθμίσεις Ημερολογίου',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'Οργανισμός',
	'SINGLE_Contacts' => 'Επαφή',
	'HelpDesk' => 'Tickets',
	'LBL_TAG_CLOUD' => 'Tag Cloud',

	'LBL_NO_RECORDS' => 'Καμμία Καταγραφή',
	'LBL_NO_RELATED' => 'Κανένας Συσχετισμός',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Only the first 100 results of all modules are shown below. For module specific results, please select respective module and search',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Only the first 100 results are shown below. Please do Advanced Search if you are not satisfied with the result',

	// used in reports detail view
	'LBL_ACTION' => 'Ενέργεια',
	'LBL_NOTE' => 'Σημείωση',
	'LBL_SELECT_OPTION' => 'Επιλέξτε μία Επιλογή',

	//Module Manager
	'LBL_TOOLTIP' => 'Διαχείρηση Αναδυόμενης Βοήθειας',
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Αρίθμηση Συχνότητας Module',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Εξατομίκευση Χαρτογράγησης Πεδίου',
	'LBL_WEBFORMS' => 'WebForms',

	//Compose Email Strings
	'SINGLE_Emails' => 'Email',
	'Emails' => 'Ηλεκτρονικά Μηνύματα',
	'LBL_SELECT_EMAIL_IDS' => 'Επιλογή Ηλ.Διεύθυνσης',
	'LBL_SUBJECT' => 'Θέμα',
	'LBL_ATTACHMENT' => 'Επισυναπτόμενο',
	'LBL_BROWSE_CRM' => 'Browse CRM',
	'LBL_SEND' => 'Αποστολή',
	'LBL_SAVE_AS_DRAFT' => 'Αποθήκευση ως Πρόχειρο',
	'LBL_GO_TO_PREVIEW' => 'Προεπισκόπηση',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Επιλογή Σχεδίου Email',
	'LBL_COMPOSE_EMAIL' => 'Σύνταξη Ηλ.Μηνύματος',
 	'LBL_CC' => 'Cc',
   	'LBL_BCC' => 'Bcc',
   	'LBL_ADD_CC' => 'Προσθήκη Cc',
   	'LBL_ADD_BCC' => 'Προσθήκη Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Ανώτατο όριο ',
	'LBL_EXCEEDED' => 'Υπερβαίνει',
	'LBL_OPERATION_NOT_PERMITTED' => 'Η ενέργεια Δέν Επιτρέπετε',
    'LBL_MERGE' => 'Συγχώνευση',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Επιλογή Κριτηρίων Συγχώνευσης',
	'LBL_AVAILABLE_FIELDS' => 'Διαθέσιμα Πεδία',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'The primary record will be retained after the merge. You can select the column to retain the values.
										The other record will be deleted but the related information will be merged.',
	'LBL_MERGE_RECORDS_IN' => 'Συγγχωνευμένες Καταγραφές στίς',
	'LBL_FIELDS' => 'Πεδία',
	'LBL_RECORD' => 'Καταγραφή',
	'LBL_NO_DUPLICATED_FOUND' => 'Δέν Βρέθηκαν Διπλότυπτα',
	'LBL_MERGE_SELECT' => 'Συγχώνευση Επιλεγμένων',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Πίσω στα Προϊόντα',

	//Translations used for Export to Pdf
	'Valid Date' => 'Έγκυρη Ημερομηνία',
	'Phone: ' => 'Τηλ: ',
	'Issued Date' => 'Ημερομηνία Έκδοσης',
	'Shipping & Handling Charges' => 'Χρεώσεις Αποστολής και Μεταφοράς',
	'Shipping & Handling Tax:' => 'Φόρος Αποστολής και Μεταφοράς:',
	'Discount'=>'Έκπτωση',
	'Net Total' => 'Καθαρή Αξία',
	'Product Code'=>'Κωδ.Προϊόντος',
	'Customer Name'=>'Όνομα Πελάτη',
	'Price'=>'Τιμή',
	'Tax:' => 'Φ.Π.Α:',
	'Contact Name' => 'Όνομα Επικοινωνίας',
	'Grand Total:' => 'Γενικό Σύνολο:',
	'Fax: ' => 'Fax: ',
	'Website: ' => 'Ιστοσελίδα: ',
	'Tax' => 'Φόρος',
	'LBL_ALPHABETS' => 'Α,Β,Γ,Δ,Ε,Ζ,Η,Θ,Ι,Κ,Λ,Μ,Ν,Ξ,Ο,Π,Ρ,Σ,Τ,Υ,Φ,Χ,Ψ,Ω,',

	//Realted tab strings
	'Service Contracts' => 'Συμβόλαια Υπηρεσιών',
	'Projects' => 'Έργα',
	'Sales Order' => 'Διαταγή Πώλησης',
	'Purchase Order' => 'Διαταγή Αγοράς',
	'List and Campaigns' => 'Λίστα και Εκστρατείες',
	'Project Tasks' => 'Εργασίες Project',
	'Project Milestones' => 'Project Milestones',

	'Labels Editor' => 'Επεξεργαστής Ετικέτων',
	'LBL_IGNORE_EMPTY_VALUES' =>'Παράβλέψη Κενών Τιμών',

	//Related tabs of Products
	'Product Bundles' => 'Product Bundles',
	'Parent Product' => 'Parent Product',

	'LBL_MANAGE_USERS' => 'Διαχείρηση Χρηστών',
	'LBL_TRANSFER_OWNERSHIP' => 'Μεταβίβαση Κυριότητας',
	'LBL_SELECT_RELATED_MODULES' => 'Επιλέξτε Σχετικά Modules',
	'LBL_ASSIGNED_TO' => 'Ανατεθειμένα σε/στον',

	//Report Detail View
	'LBL_VIEW_DETAILS' => 'Δείτε Λεπτομέρειες',
	//Comments Field Labels for Workflow
	'Comment' => 'Σχόλιο',
	'Last Comment' => 'Τελευταίο Σχόλιο',
	'Last 5 Comments' => 'Τελευταία 5 Σχόλια',
	'All Comments' => 'Όλα τα Σχόλια',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Παρακαλώ Διαμορφώστε τίς Ρυθμίσεις του εξωτερικού server απο την Σελίδα ΡΥΘΜΙΣΕΙΣ',
	'JS_SMS_SERVER_CONFIGURATION' => 'Παρακαλώ Διαμορφώστε τίς Ρυθμίσεις  τής Ειδοποίησης Μηνυμάτων(sms) απο την Σελίδα ΕΙΔΟΠΟΙΗΣΕΙΣ ΜΗΝΥΜΑΤΩΝ SMS',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Παρακαλώ Επιλέξτε Τουλάχιστον Μία Εγγραφή',

	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Παρακαλώ Εισάγετε Έναν Έγκυρο Ηλ.Λογαριασμό',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'Περιέχει Άγνωστους Χαρακτήρες',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'Υπέρβαση Ορίου Αριθμών Του Τηλεφωνικού Αριθμού',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Επιτρέπονται Μόνο Θετικές Τιμές',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'Η τιμή Πρέπει να Είναι Μεγαλύτερη Του Μηδενός',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Ο Αριθμός Πρέπει Να Είναι Μικρότερος του 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Παρακαλώ Εισάγετε Μία Έγκυρη Ημερομηνία',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Παρακαλώ Εισάγετε Μία Έγκυρη Ωρα',
	'JS_INVALID_PAGE_NUMBER' => 'Μή Έγκυρος Αρ.Σελίδος',


	'INVALID_NUMBER_OF' => 'Μή Έγκυρος Αριθμός από',
	'INVALID_NUMBER' => 'Μή Έγκυρος Αριθμός',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Είστε Σίγουρος/η οτι Θέλετε Να Διαγράψετε;',

	'OVERWRITE_EXISTING_MSG1' => 'Επανεγγραφή της Διευθύνσεως με την Επιλεγμένη; ',
	'OVERWRITE_EXISTING_MSG2' => 'Στοιχεία Διευθύνσεως;',
	'SINGLE_Accounts' => 'Οργανισμός',
	'SINGLE_Contacts' => 'Επαφή',

	'LBL_DELETE_CONFIRMATION' => 'Είστε Σίγουρος/η για την Διαγραφή;', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_MASS_DELETE_CONFIRMATION' => 'Είστε Σίγουρος/η για την Διαγραφή των Επιλεγμένων Εγγραφών;',
	'JS_LBL_SAVE' => 'Αποθήκευση',
	'JS_LBL_CANCEL' => 'Ακύρωση',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Το Όνομα του Όργανισμού Υπάρχει ήδη.Θέλετε να Δημιουργήσετε ένα Αντίγραφο;',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Πρέπει να Συμβεί Πρίν Απο Το Σήμερα',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Παρακαλώ Επιλέξτε Τουλάχιστον Μία Επιλογή',
	'JS_SELECT_MODULE' => 'Παρακαλώ Επιλέξτε Module',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Παρακαλώ Επιλέξτε Τουλάχιστο Ένα Υποχρεωτικό Πεδίο',
	'JS_SELECT_MODULE' => 'Παρακαλώ Επιλέξτε Ένα Module',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Παρακαλώ Εισάγετε  μια Ακέραιη Τιμή',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Παρακαλώ Εισάγετε μια Δεκαδική Τιμή',

	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'Πρέπει να είναι Κοντινότερη από την σημερινή Ημερομηνία',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'Πρέπει να είναι Μακρινότερη από την Σημερινή Ημερομηνία',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'Θα Πρέπει να είναι Μεγαλύτερο η Ίσο',
    'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'Θα Πρέπει να είναι Μικρότερο η Ίσο',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Η Επί τίς Εκατό τιμή Θα Πρέπει να είναι Μικρότερη απο 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Αποδεκτοί Μόνον Αριθμοί',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'Αυτός ο Φάκελος έχει ήδη Επιλεχθεί',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'Υπέρβαση Ορίου Μεγέθους Αρχείου πρός Ανέβασμα',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'Αυτό το Έγγραφο έχει ήδη Επιλεγεί',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'Θα Πρέπει να Έινα Μεγαλύτερο η Ίσο με',


	//Roles
	'JS_FAILED_TO_SAVE' => 'Απέτυχε η Αποθήκευση στόν Server',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Ο Φάκελος πρός Εισαγωγή Δέν μπορεί να είναι Κενός',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Επιλέηξτε Τουλάχιστον Ένα Πεδιό για την Συγχώνευση',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Ο Χάρτης Δέν Μπορεί Να Έιναι Κενός',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Το Όνομα του Χάρτη Υπάρχει ήδη',
	'JS_SELECT_FILE_EXTENSION' => 'Παρακαλώ επιλέξτε ένα αρχείο με τήν παρακάτω επέκταση',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Το Μέγεθος του Αρχείου πρός Ανέβασμα Πρέπει να είναι Μικρότερο απο',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Το Ανεβασμένο Αρχείο Υπάρχει ήδη',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Παρακαλω Χωρίστε το Αρχείο σε Μικρότερα Κομμάτια και Εισάγετε Ξανά',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Το Πεδίο Χαρτογραφήθηκε Παραπάνω απο Μία Φορά',
	'JS_MAP_MANDATORY_FIELDS' => 'Παρακαλώ Χαρτογραφήστε τα Απαραίτητα Πεδία',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Παρακαλω Εισάγετε Μία Τιμή Πρός Αναζήτηση',

	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'Μπορείτε να Επιλέξετε Μόνο',
	'JS_ITEMS' => 'Αντικείμενα',

	'JS_LBL_PERMISSION' => 'Άδειες Προσβάσεως',
	'JS_CHECK_FILE_INTEGRITY' => 'Έλεγχος Ακεραιότητας Αρχείου',
	'JS_DUPLICATE_RECORD' => 'Αντιγράψτε το Αρχείο',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'Είναι Ενεργό',
	'JS_IS_DISABLED' => 'Είναι Ανενεργό',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Παρακαλω Γράψτε Κάποιο Κείμενο για Σχολιασμό',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Η Τιμή Του Σχολιασμού Δέν Μπορεί να Είναι Κενή',
	'JS_REQUIRED_FIELD' => '* Αυτό το Πεδίο είναι Απαραίτητο',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Δέν Μπορείτε να Αφαιρέσετε το Προεπιλεγμένο Widget',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'Πρέπει να είναι Μικρότερη απο τήν Τρέχων Ημερομηνία',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'No create permissions or not enabled for quick create',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Η Εικόνα Διαγράφηκε Επιτυχώς',
	'LBL_IMAGE_NOT_DELETED' => 'Η Εικόνα Δέν Διαγράφηκε',
	'LBL_YES' => 'Ναι',
	'LBL_NO' => 'Όχι',
	'AM' => 'ΠΜ',
	'PM' => 'ΜΜ',
 	'JS_ERROR' => 'Λάθος',
	'JS_INFORMATION' => 'Πληροφορία',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'Δέν έχει Διευ.Ηλεκτρονικού Ταχυδρομείου',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'None of the field values are changed in Mass Edit',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Παρακαλώ Επιλέξτε Έναν Οργανισμό για Αντιγραφή τής Διεύθυνσης',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Παρακαλώ Επιλέξτε Μία Επαφή για Αντιγραφή τής Διεύθυνσης',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Ο Επιλεγμένος Οργανισμός Δέν Περιέχει Διεύθυνση για Αντιγραφή',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Η Επιλεγμένη Επαφή Δέν Περιέχει Διεύθυνση για Αντιγραφή',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Παρακαλώ Εισάγετε το Πρωτεύον Email για την Ενεργοποίηση τής Πύλης Χρηστών',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Το Πρωτεύον Email Δεν Υπάρχει για τήν Ενεργοποίηση της Πύλης Χρηστών.',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Παρακαλώ Εισάγετε μία Ετικέτα',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Το Όνομα της Ετικέτας Υπάρχει ήδη',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Υπέρβαση Ορίου Χαρακτήρων Ετικέτας',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Δεν θα έχετε το Δικαίωμα να δείτε την Καταγραφή μετά την Αποθήκευση. Επιθυμήτε να συνεχίσετε;',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'Καμμία Καταγραφή Δέν Σχετίζετε με Αυτό το Φίλτρο',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Ημ.Έναρξης και Ώρα',
	'JS_END_DATE_TIME' => 'Ημ.Λήξης και ώρα',
	'JS_POSTPONE' => 'Αναβολή',
	'JS_MESSAGE' => 'Μήνυμα',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Δεν θα έχετε το Δικαίωμα να δείτε την Καταγραφή μετά την Αποθήκευση. Επιθυμήτε να συνεχίσετε;',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Η Συντόμευση Εισήχθει Επιτυχώς',
	'JS_SUCCESSFULLY_UNPINNED' => 'Η Συντόμευση Αφαιρέθηκε Επιτυχώς',
	'JS_SHORTCUT_ALREADY_ADDED' => 'Αυτή η Συντόμευση Έχει Ήδη Εισαχθεί',
	'JS_MESSAGE' => 'Μήνυμα',

	//Module Manager
	'JS_MODULE_ENABLED' => 'Module Ενεργό',
	'JS_MODULE_DISABLED' => 'Module Ανενεργό',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Η διαμόρφωση της Συχνότητας τών Προγραμματισμένων Εργασίων Δεν Μπορεί να Είναι Μικρότερη απο',
	'JS_MINUTES' => 'Λεπτά',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Το Αντικείμενο Μετανομάστηκε Επιτυχώς',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Το Αντικείμενο Προστέθηκε Επιτυχώς',
	'JS_NO_ITEM_SELECTED' => 'Κανένα Επιλεγμένο Αντικείμενο',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'Περισσότερα απο Ένα Αντικείμενα Έχουν Επιλεχθεί',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Το Αντικείμενο Διαγράφτηκε Επιτυχώς',
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Διπλότυπες Καταχωρήσεις Βρέθηκαν Για την Ίδια Τιμή',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Πρέπει να Επιλέξετε Καταγραφές για Συγχώνευση Από την Ίδια Ομάδα',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Επιλέξτε Τουλάχιστον Δύο Εγγραφές Για Συγχώνευση',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Το Επιτρεπόμενο Ανώτατο Όριο Επιλογής Είναι Τρείς Εγγραφές',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Είστε Σίγουροι ότι θέλετε να διαγράψετε το widget',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Διπλότυπες εγγραφές Βρέθηκαν για την ίδια Τιμή',
	'JS_TOTAL_RECORDS' => 'Συνολικές Εγγραφές',
	'JS_PAGE_NOT_EXIST' => 'Η Σελίδα Δέν Υπάρχει ',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'Βρίσκεστε Στην Σελίδα Νούμερο',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Παρακαλώ Ενεργοποιήστε Την Βασική Ισοτιμία για το Προϊόν',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Παρακαλώ Επιλέξτε Την Βασική Ισοτιμία για το Προϊόν',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Οι Καταγραφές Αρχίζουν Να Διαγράφονται',
	'JS_RECORD_GETTING_DELETED' => 'Η Καταγραφή Αρχίζει να Διαγράφετε',
	'JS_NO_RESULTS_FOUND' => 'Δέν Βρέθηκε Κανένα Αποτέλεσμα',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Οι Καταγραφές Ιδιοκτησίας Μεταφέρθηκαν Επιτυχώς',

	'JS_USER_EXISTS' => 'Αυτός Ο Χρήστης Υπάρχει ήδη',
	'JS_REENTER_PASSWORDS' => 'Εισάγετε Ξανά τούς Κωδικούς',
);
