<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'vtiger CRM',
	'POWEREDBY'=> 'Powered by vtiger CRM',
	'LBL_READ_LICENSE' => 'Read License',
	'LBL_PRIVACY_POLICY' => 'Privacy Policy',

	// Common Actions
	'LBL_SELECT_ALL' => 'Select all',
	'LBL_SELECT_TO_LOAD_LIST' => 'Select to Load List',
	'LBL_CREATING_NEW' => 'Creating New',
	'LBL_EDITING' => 'Editing',
	'LBL_SAVE' => 'Save',
	'LBL_CANCEL' => 'Cancel',
	'LBL_BACK' => 'Back',
	'LBL_IMPORT' => 'Import',
	'LBL_EXPORT' => 'Export',
	'LBL_FIND_DUPLICATES' => 'Find Duplicates',
	'LBL_MORE' => 'More',
	'LBL_ACTIONS' => 'Actions',
    'LBL_ADD' => 'Add',
	'LBL_EDIT' => 'Edit',
	'LBL_DELETE' => 'Delete',
	'LBL_SETTINGS'=> 'Settings',
	'LBL_ADD_COMMENT' => 'Add Comment',
	'LBL_EDIT_FIELDS' => 'Edit Fields',
	'LBL_EDIT_WORKFLOWS' => 'Edit Workflows',
	'LBL_EDIT_PICKLIST_VALUES' => 'Edit Picklist Values',
	'LBL_EDIT_MAILSCANNER' => 'Mail Converter',
	'LBL_RECORD_DELETE' => 'The record you are trying to view has been deleted.',
	'LBL_RECORD_NOT_FOUND' => 'Record you are trying to access is not found',
	'LBL_EDIT_REASON' => 'Edit reason',

	//'LBL_EDIT_CURRENT_FILTER' => 'Edit Current Filter',
	//'LBL_DELETE_CURRENT_FILTER' => 'Delete Current Filter',
	'LBL_SELECT' => 'Select',
	'LBL_CLEAR' => 'Clear',
	'LBL_YES' => 'Yes',
	'LBL_NO' => 'No',
	'LBL_SHOW_COMPLETE_DETAILS' => 'Complete Details',
    'LBL_MASS_EDITING' => 'Mass Editing',
	'LBL_DESELECT_ALL_RECORDS' => 'Deselect All Records',
	'LBL_QUICK_CREATE' => 'Quick Create',
	'LBL_SEND_EMAIL' => 'Send Email',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'All email accounts',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Please select one of the options below',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'Go to full form',
	'LBL_SEND_SMS' => 'Send SMS',
	'LBL_FOUND' => 'found',
	'LBL_CLICK_ADD' => 'Click add',
	'LBL_ADD_MORE_FIELDS' => 'Add more fields',
	'LBL_ADD_NOTE' => 'Add Document',
	'LBL_CREATE_NEW' => 'Create New',
    'LBL_ADD_EVENT' => 'Add Event',
    'LBL_ADD_TASK' => 'Add Task',
	'LBL_MARKETING_AND_SALES' => 'MARKETING & SALES',
	'LBL_TOOLS_HEADER' => 'TOOLS',
	'LBL_SUPPORT' => 'SUPPORT',
	'LBL_INVENTORY' => 'INVENTORY',
	'LBL_ANALYTICS' => 'ANALYTICS',
	'LBL_HOME' => 'Home',

	// Common Link Labels
	'LBL_LAST_VIEWED_RECORDS' => 'Last Viewed Records',
	'LBL_DASHBOARD' => 'Dashboard',
	'LBL_USER_SETTINGS' => 'User Settings',
	'LBL_MY_PREFERENCES' => 'My Preferences',
	'LBL_SIGN_OUT' => 'Sign Out',
	'LBL_HELP' => 'Help',
	'LBL_DOCUMENTATION' => 'Documentation',
	'LBL_VIDEO_TUTORIAL' => 'Video Tutorial',
	'LBL_FEEDBACK' => 'Feedback',
	'LBL_CRM_SETTINGS' => 'CRM Settings',
	'LBL_ON_DEMAND_ADMIN' => 'Add / Delete Users',
	'LBL_ANNOUNCEMENT' => 'Announcement',
	'LBL_CALENDAR' => 'Calendar',
	'LBL_POST' => 'Post',
	'LBL_GUIDER' => 'Guider',
	'LBL_DISPLAY_TYPE' => 'Display Type',
	'LBL_DISPLAY_WIDETYPE' => 'Wide',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Medium',
	'LBL_DISPLAY_NARROWTYPE' => 'Narrow',
	'LBL_TAG_THIS_RECORD' => 'Tag this Record',
	'LBL_PAGE' => 'Page',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Page Jump',
	'LBL_PROFILE_PASSWORD' => 'Profile / Password',

	// Common Fields
	'LBL_USER' => 'User',
	'LBL_GROUP' => 'Group',
	'Last Modified By' => 'Last Modified By',
	'Created Time' => 'Created Time',
	'Modified Time' => 'Modified Time',
	'Description' => 'Description',
	'Assigned To'=>'Assigned To',

	//Loading Labels
	'LBL_LOADING' => 'Loading',
	'LBL_LOADING_WIDGET' => 'Loading Widget',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'Loading, Please wait.',

	// Detail View
	'LBL_UPDATES' => 'Updates',
	'LBL_SHOW_FULL_DETAILS' => 'Show Full Details',
	'LBL_SUMMARY_DETAILS' => 'Summary Details',
	'LBL_ADD_NEW_COMMENT' =>'Add New Comment',
	'LBL_NO_UPDATES' => 'No Updates',
	'LBL_ACTIVITIES' => 'Activities',
	'LBL_NO_PENDING_ACTIVITIES' => 'No pending activities',
	'LBL_SUMMARY' => 'Summary',
	'LBL_DETAILS' => 'Details',

	// Popup window
	'LBL_SEARCH_FOR' => 'Search For',
	'LBL_IN' => 'in',
	'LBL_TYPE_SEARCH' => 'Type to search',
	'LBL_SEARCH_BUTTON' => 'Search Button',
	'LBL_ADVANCE_SEARCH' => 'Advanced',
	'LBL_LOADING_PLEASE_WAIT' => 'Loading, Please wait.',
	'LBL_PLEASE_SELECT_MODULE' => 'Please select module',

	//DropDown Category
	'LBL_USERS' => 'Users',
	'LBL_GROUPS' => 'Groups',

	//EditView Form Links
	'LBL_FULL_FORM' => 'Full Form',
	'LBL_SIMPLE_FORM' => 'Simple Form',

	//Recent Comments
	'LBL_ADD_YOUR_COMMENT_HERE' => 'Add your comment here...',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Reason for changing comment',
	'LBL_REPLY' => 'Reply',
	'LBL_VIEW_THREAD' => 'View Thread',
	'LBL_NO_COMMENTS' => 'No comments',
	'LBL_REPLIES' => 'replies',

	//Translation for all modules
	'Accounts' => 'Organizations',
	'Assets' => 'Assets',
	'Calendar' => 'Calendar',
	'Campaigns' => 'Campaigns',
	'Contacts' => 'Contacts',
	'Documents' => 'Documents',
	'Leads' => 'Leads',
	'ModComments' => 'Comments',
	'Potentials' => 'Opportunities',
	'PriceBooks' => 'Price Books',
	'Products' => 'Products',
	'Project' => 'Projects',
	'ProjectMilestone' => 'Project Milestones',
	'ProjectTask' => 'Project Tasks',
	'ServiceContracts' => 'Service Contracts',
	'Services' => 'Services',
	'Vendors' => 'Vendors',
	'Rss' => 'RSS',
	'Quotes'=>'Quotes',
	'PurchaseOrder'=>'Purchase Order',
	'SalesOrder'=>'Sales Order',
	'Invoice'=>'Invoice',
	'MailManager' => 'Mail Manager',
	'Activities' => 'Activities',


	//Basic String Translation
	'LBL_ADD_RECORD' => 'Add Record',
	'LBL_RECENTLY_MODIFIED' => 'Recently Modified',
	'LBL_RECORDS_LIST' => 'Records List',
	'LBL_RECORD_SUMMARY' => 'Module Summary',
	'LBL_RECORD_SUMMARY' => 'Module Details',
	'LBL_ACCESS_DENIED_FOR' => 'Access Denied for',
	'LBL_GO_BACK' => 'Go back',
	'LBL_NO_DATA_AVAILABLE' => 'No data available',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'Type keyword and press enter',
	'LBL_ALL_RECORDS' => 'All Records',
	'LBL_NO_RECORDS_FOUND' => 'No records found',

	//Filters & Advance Filter
	'LBL_AND' => 'and',
	'LBL_OR' => 'or',
	'LBL_NONE' => 'NONE',
	'LBL_APPROVE' => 'Approve',
	'LBL_DENY' => 'Deny',
	'LBL_EQUALS' => 'equals',
	'LBL_NOT_EQUAL_TO' => 'not equal to',
	'LBL_STARTS_WITH' => 'starts with',
	'LBL_ENDS_WITH' => 'ends with',
	'LBL_CONTAINS' => 'contains',
	'LBL_DOES_NOT_CONTAIN' => 'does not contains',
	'LBL_LESS_THAN' => 'less than',
	'LBL_GREATER_THAN' => 'greater than',
	'LBL_LESS_THAN_OR_EQUAL' => 'less or equal',
	'LBL_GREATER_OR_EQUAL' => 'greater or equal',
	'LBL_BEFORE' => 'before',
	'LBL_AFTER' => 'after',
	'LBL_BETWEEN' => 'between',
	'LBL_SEARCH' => 'Search',
	'LBL_SEARCH_IN' => 'Search In',
	'LBL_ADD_CONDITION' => 'Add Condition',
	'LBL_ADD_GROUP' => 'Add Condition Group',
	'LBL_FILTER_CONDITIONS' => 'Filter Conditions',
	'LBL_ALL_CONDITIONS' => 'All Conditions',
	'LBL_ALL_CONDITIONS_DESC' => 'All conditions must be met',
	'LBL_ANY_CONDITIONS' => 'Any Conditions',
	'LBL_ANY_CONDITIONS_DESC' => 'At least one of the conditions must be met',
	'LBL_SELECT_FIELD' => 'Select Field',
	'LBL_SELECT_MODULE' => 'Select Module',
	'LBL_CREATE_NEW_FILTER' => 'Create New Filter',
	'All' => 'All',
	'Others' => 'Others',
	'Pending' => 'Pending',
	'Public' => 'Public',

	//Advance Search
	'LBL_SAVE_FILTER' => 'Save Filter',
	'LBL_SAVE_MODIFY_FILTER' => 'Save/Modify Filter',
	'LBL_SEARCH_RESULTS' => 'Search Results',
	'LBL_SAVE_AS_FILTER' => 'Save As Filter',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Access denied',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'Item Details',
	'LBL_CURRENCY' => 'Currency',
	'LBL_TAX_MODE' => 'Tax Mode',
	'LBL_INDIVIDUAL' => 'Individual',
	'LBL_GROUP' => 'Group',
	'LBL_TOOLS' => 'Tools',
	'LBL_ITEM_NAME' => 'Item Name',
	'LBL_QTY_IN_STOCK' => 'Stock',
	'LBL_QTY' => 'Quantity',
	'LBL_LIST_PRICE' => 'List Price',
	'LBL_TOTAL' => 'Total',
	'LBL_NET_PRICE' => 'Net Price',
	'LBL_DISCOUNT' => 'Discount',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Total After Discount',
	'LBL_TAX' => 'Tax',
	'LBL_ADD_PRODUCT' => 'Add Product',
	'LBL_ADD_SERVICE' => 'Add Service',
	'LBL_ITEMS_TOTAL' => 'Items Total',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Shipping & Handling Charges',
	'LBL_PRE_TAX_TOTAL' => 'Pre Tax Total',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Taxes For Shipping and Handling',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Set S&H Taxes For',
	'LBL_ADJUSTMENT' => 'Adjustment',
	'LBL_DEDUCT' => 'Deduct',
	'LBL_GRAND_TOTAL' => 'Grand Total',
	'LBL_ZERO_DISCOUNT' => 'Zero Discount',
	'LBL_OF_PRICE' => 'Price',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Direct Price Reduction',
	'LBL_SET_DISCOUNT_FOR' => 'Set Discount For',
	'LBL_STOCK_NOT_ENOUGH' => 'Not enough stock',
	'LBL_MAX_QTY_SELECT' => 'Maximum value is',
	'LBL_DRAG' => 'Drag',
	'LBL_TOTAL_TAX_AMOUNT' => 'Total Tax Amount',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Direct Amount Discount',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Final Discount Amount',
	'LBL_MORE_CURRENCIES' => 'more currencies',
	'LBL_SET_TAX_FOR' => 'Set Tax for',
	'LBL_GROUP_TAX' => 'Group Tax',
	'LBL_BILLING_ADDRESS_FROM' => 'Copy Billing Address from',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Copy Shipping Address from',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Shipping Address',
	'LBL_COPY_BILLING_ADDRESS' => 'Billing Address',

	//DetailView Actions
	'LBL_CREATE' => 'Create',
	'LBL_GENERATE' => 'Generate',
    'LBL_DUPLICATE' => 'Duplicate',
	'Add Note' => 'Add Document',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Add Widget',
	'LBL_COMMENTS' => 'Comments',
	'LBL_REFRESH' => 'Refresh',
	'LBL_CLOSE' => 'Close',
	'LBL_ALL' => 'All',
	'LBL_UPDATED' => 'updated',
	'LBL_FROM' => 'from',
	'LBL_TO' => 'to',
	'LBL_to' => 'to',
	'LBL_ON' => 'on',
	'LBL_OF' => 'of',
	'LBL_BY' => 'by',
	'LBL_ADDED' => 'added',
	'LBL_FOR' => 'for',
	'LBL_CREATED' => 'created',
	'LBL_DELETED' => 'deleted',
	'LBL_RESTORED' => 'restored',
	'LBL_COMMENTED' => 'commented',
	'LBL_REMOVED' => 'removed',
	'LBL_REMOVE' => 'Remove',
	'LBL_AT' => 'at',
	'LBL_MINE' => 'Mine',
	'History' => 'History',
	'Upcoming Tasks' => 'Upcoming Tasks',
	'LBL_YEAR' => 'year',
	'LBL_YEARS' => 'years',
	'LBL_MONTH' => 'month',
	'LBL_MONTHS' => 'months',
	'LBL_DAY' => 'day',
	'LBL_DAYS' => 'days',
	'LBL_HOUR' => 'hour',
	'LBL_HOURS' => 'hours',
	'LBL_MINUTE' => 'minute',
	'LBL_MINUTES' => 'minutes',
	'LBL_SECOND' => 'second',
	'LBL_SECONDS' => 'seconds',
	'LBL_JUSTNOW' => 'just now',
	'LBL_CUSTOM_INFORMATION' => 'Custom Information',
	'LBL_NO_RECENT_UPDATES' => 'No recent updates',
	'LBL_NO_DATA' => 'No Data',
	'LBL_PERMISSION_DENIED' => 'Permission denied',
	'LBL_HANDLER_NOT_FOUND' => 'Handler not found',
	'LBL_FILTER' => 'Filter',
	'LBL_DUE' => 'due in',
	'LBL_DAYS' => 'days',
	'LBL_COMPLETED' => 'completed',
	'LBL_AGO' => 'ago',
	'LBL_CHANGED' => 'changed',
	'Single_Users' => 'User',
	'LBL_MATCHED_THIS_CRITERIA'=> 'matched this criteria',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'No scheduled activities',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'No overdue activities',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'No updates or comments',
	'LBL_MINI_LIST' => 'Mini List',
	'LBL_NOTEPAD' => 'Notepad',
	'LBL_NOTEPAD_NAME' => 'Notepad Name',
	'LBL_NOTEPAD_CONTENT' => 'Notepad Content',
	'LBL_LAST_SAVED_ON' => 'Last saved on',
	'Mini List' => 'Mini List',
	'Notebook' => 'Notepad',
	'LBL_RESULT_FOR_THE_TAG' => 'Results for the tag',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'View Name',
	'LBL_CREATE_VIEW' => 'Creating new View',
	'LBL_BASIC_DETAILS' => 'Basic Details',
	'LBL_CHOOSE_COLUMNS' => 'Choose Columns and Order',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Max 12',
	'LBL_FILTER_ON_DATE' => 'Filter on date',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Choose filter Conditions',
	'LBL_ADD_CONDITION' => 'Add Condition',
	'LBL_SET_AS_DEFAULT' => 'Set as Default',
	'LBL_LIST_IN_METRICS' => 'List in Metrics',
	'LBL_SET_AS_PUBLIC' => ' Set as Public',
	'LBL_AND' => 'and',
	'LBL_OR' => 'or',
	'LBL_ADD_MORE_COLUMNS' => 'Add more Columns',
	'LBL_ADD_GROUP' => 'Add Group',


	//DateFilter Conditions
	'LBL_CUSTOM' => 'Custom',
	'LBL_PREVIOUS_FY' => 'Previous FY',
	'LBL_CURRENT_FY' => 'Current FY',
	'LBL_NEXT_FY' => 'Next FY',
	'LBL_PREVIOUS_FQ' => 'Previous FQ',
	'LBL_CURRENT_FQ' => 'Current FQ',
	'LBL_NEXT_FQ' => 'Next FQ',
	'LBL_YESTERDAY' => 'Yesterday',
	'LBL_TODAY' => 'Today',
	'LBL_TOMORROW' => 'Tomorrow',
	'LBL_LAST_WEEK' => 'Previous Week',
	'LBL_CURRENT_WEEK' => 'Current Week',
	'LBL_NEXT_WEEK' => 'Next Week',
	'LBL_LAST_MONTH' => 'Previous Month',
	'LBL_CURRENT_MONTH' => 'Current Month',
	'LBL_NEXT_MONTH' => 'Next Month',
	'LBL_LAST_7_DAYS' => 'Last 7 Days',
	'LBL_LAST_30_DAYS' => 'Last 30 Days',
	'LBL_LAST_60_DAYS' => 'Last 60 Days',
	'LBL_LAST_90_DAYS' => 'Last 90 Days',
	'LBL_LAST_120_DAYS' => 'Last 120 Days',
	'LBL_NEXT_30_DAYS' => 'Next 30 Days',
	'LBL_NEXT_60_DAYS' => 'Next 60 Days',
	'LBL_NEXT_90_DAYS' => 'Next 90 Days',
	'LBL_NEXT_120_DAYS' => 'Next 120 Days',

	//advanced Filter Options
	'LBL_NONE' => 'NONE',
	'LBL_EQUALS' => 'equals',
	'LBL_NOT_EQUAL_TO' => 'not equal to',
	'LBL_STARTS_WITH' => 'starts with',
	'LBL_ENDS_WITH' => 'ends with',
	'LBL_CONTAINS' => 'contains',
	'LBL_DOES_NOT_CONTAIN' => 'does not contains',
	'LBL_LESS_THAN' => 'less than',
	'LBL_GREATER_THAN' => 'greater than',
	'LBL_LESS_THAN_OR_EQUAL' => 'less or equal',
	'LBL_GREATER_OR_EQUAL' => 'greater or equal',
	'LBL_BEFORE' => 'before',
	'LBL_AFTER' => 'after',
	'LBL_BETWEEN' => 'between',
	'LBL_IS_EMPTY'=> 'is empty',

	//Detail view summary widgets
	'LBL_OWNER' => 'Owner',
	'LBL_CREATED_ON' => 'Created On',
	'LBL_MODIFIED_ON' => 'Modified On',
	'LBL_MODIFIED' => 'Modified',
	'LBL_COMMENTED' => 'Commented',

    //calender set-reminder
    'LBL_BEFORE_EVENT' => ' Before Event',

	//Dashboard widgets
	'History' => 'History',
	'Upcoming Activities' => 'Upcoming Activities',
	'Overdue Activities' => 'Overdue Activities',
	'Funnel' => 'Funnel',
	'Potentials by Stage' => 'Opportunities by Stage',
	'Pipelined Amount' => 'Sales Pipeline',
	'Total Revenue' => 'Total Revenue',
	'Top Potentials' => 'Top Opportunities',
	'Forecast' => 'Forecast',
	'Leads Created' => 'Leads Created',
	'Leads by Status' => 'Leads by Status',
	'Leads by Source' => 'Leads by Source',
	'Leads by Industry' => 'Leads by Industry',
	'Tickets by Status' => 'Tickets by Status',
	'Open Tickets' => 'Open Tickets',
	'Funnel Amount' => 'Total Amount by Sales stage',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'Export all data',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Export data in current page',
	'LBL_EXPORT_SELECTED_RECORDS' => 'Export Selected Records',
	'LBL_EXPORT_RECORDS' => 'Export Records',
	'LBL_NO_RECORD_SELECTED' => 'No record selected.',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove default widget',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'filter already exists',

	'LBL_ADD_MANAGE_MODULES' => 'Add / Manage Modules',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Customize Main Menu',

	// Added Common Keys for all modules
	'Account Name' => 'Organization Name',
	'Add Comment' => 'Add Comment',
	'Adjustment' => 'Adjustment',
	'Annual Revenue' => 'Annual Revenue',
	'Apparel'=>'Apparel',
	'Banking'=>'Banking',
	'Billing Address' => 'Billing Address',
	'Billing City' => 'Billing City',
	'Billing Code' => 'Billing Postal Code',
	'Billing Country' => 'Billing Country',
	'Billing Po Box' => 'Billing PO Box',
	'Billing State' => 'Billing State',
	'Biotechnology'=>'Biotechnology',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Carrier',
	'Category'=>'Category',
	'Chemicals'=>'Chemicals',
	'City' => 'City',

	'Cold Call'=>'Cold Call',
	'Existing Customer'=>'Existing Customer',
	'Self Generated'=>'Self Generated',
	'Employee'=>'Employee',
	'Partner'=>'Partner',
	'Public Relations'=>'Public Relations',
	'Direct Mail'=>'Direct Mail',
	'Conference'=>'Conference',
	'Trade Show'=>'Trade Show',
	'Web Site'=>'Web Site',
	'Word of mouth'=>'Word of mouth',
	'Other'=>'Other',

	//for leads and accounts
	'--None--'=>'--None--',
	'Acquired'=>'Acquired',
	'Active'=>'Active',
	'Market Failed'=>'Market Failed',
	'Project Cancelled'=>'Project Cancelled',
	'Shutdown'=>'Shutdown',
	'Apparel'=>'Apparel',
	'Banking'=>'Banking',
	'Biotechnology'=>'Biotechnology',
	'Chemicals'=>'Chemicals',
	'Communications'=>'Communications',
	'Construction'=>'Construction',
	'Consulting'=>'Consulting',
	'Education'=>'Education',
	'Electronics'=>'Electronics',
	'Energy'=>'Energy',
	'Engineering'=>'Engineering',
	'Entertainment'=>'Entertainment',
	'Environmental'=>'Environmental',
	'Finance'=>'Finance',
	'Food & Beverage'=>'Food & Beverage',
	'Government'=>'Government',
	'Healthcare'=>'Healthcare',
	'Hospitality'=>'Hospitality',
	'Insurance'=>'Insurance',
	'Machinery'=>'Machinery',
	'Manufacturing'=>'Manufacturing',
	'Media'=>'Media',
	'Not For Profit'=>'Not For Profit',
	'Recreation'=>'Recreation',
	'Retail'=>'Retail',
	'Shipping'=>'Shipping',
	'Technology'=>'Technology',
	'Telecommunications'=>'Telecommunications',
	'Transportation'=>'Transportation',
	'Utilities'=>'Utilities',

	'Contact Name' => 'Contact Name',
	'Conversion Rate' => 'Conversion Rate',

	'Shipping Address' => 'Shipping Address',
	'Shipping City' => 'Shipping City',
	'Shipping State' => 'Shipping State',
	'Shipping Code' => 'Shipping Code',
	'Shipping Country' => 'Shipping Country',
	'Shipping Po Box' => 'Shipping PO Box',
	'Country' => 'Country',
	'Description' => 'Description',

	'Created'=>'Created',
	'Approved'=>'Approved',
	'Delivered'=>'Delivered',
	'Cancelled'=>'Cancelled',

	'Currency' => 'Currency',
	'LBL_BASE_CURRENCY' => 'Base Currency',

	'Discount Percent' => 'Discount Percent',
	'Discount Amount' => 'Discount Amount',
	'Item Discount Amount' => 'Item Discount Amount',
	'Item Discount Percent' => 'Item Discount Percent',

	'Due Date' => 'Due Date',
	'Due Date & Time' => 'Due Date & Time',
	'Email' => 'Primary Email',
	'Secondary Email' => 'Secondary Email',
	'Other Email' => 'Other Email',
	'Email Opt Out' => 'Email Opt Out',

	'Expected Close Date' => 'Expected Close Date',

	'Fax' => 'Fax',

	'Last Name' => 'Last Name',
	'First Name' => 'First Name',

	'High' => 'High',
	'Low' => 'Low',

	'In Progress' => 'In Progress',


	'Subject' => 'Subject',
	'Shipping Address'=>'Shipping Address',
	'Shipping Po Box'=>'Shipping PO Box',
	'Shipping City'=>'Shipping City',
	'Shipping State'=>'Shipping State',
	'Shipping Code'=>'Shipping Postal Code',
	'Shipping Country'=>'Shipping Country',
	'Terms & Conditions' => 'Terms & Conditions',
	'Item Name' => 'Item Name',
	'Quantity' => 'Quantity',
	'List Price' => 'List Price',
	'Item Comment' => 'Item Comment',
	'Tax1' => 'Tax1',
	'Tax2' => 'Tax2',
	'Tax3' => 'Tax3',
	'Excise Duty' => 'Excise Duty',
	'Total' => 'Total',
	'Sub Total' => 'Sub Total',
	'Tax Type' => 'Tax Type',
	'S&H Amount' => 'S&H Amount',
	'Status' => 'Status',
	'Vendor Name'=>'Vendor Name',

	'LBL_ADDRESS_INFORMATION' => 'Address Details',
	'LBL_DESCRIPTION_INFORMATION' => 'Description Details',
	'LBL_TERMS_INFORMATION' => 'Terms & Conditions',
	'LBL_PRICING_INFORMATION' => 'Pricing Information',
	'LBL_RELATED_PRODUCTS' => 'Product Details',
	'LBL_REMINDER_INFORMATION' => 'Reminder Details',

	'LBL_FOLDER_SAVED' => 'Folder saved',
	'LBL_FOLDER_EXISTS' => 'Folder already exists',
	'LBL_FOLDER_DELETED' => 'Folder deleted',

	'Lead Source' => 'Lead Source',
	'Mobile' => 'Mobile Phone',

	'Notify Owner' => 'Notify Owner',
	'Other Phone' => 'Secondary Phone',
	'Phone' => 'Primary Phone',

	'State' =>  'State',
	'Po Box' => 'PO Box',
	'Postal Code' => 'Postal Code',

	'Potential Name' => 'Opportunity Name',
	'Priority'=>'Priority',

	'Product Name' => 'Product Name',
	'Rating' => 'Rating',

	'Related To'=>'Related To',
	'Type' => 'Type',

	'Reviewed'=>'Reviewed',
	'Salutation' => 'Salutation',
	'Street' => 'Street',
	'Support Start Date' => 'Support Start Date',
	'Support Expiry Date' => 'Support Expiry Date',
	'Sales Start Date'=>'Sales Start Date',
	'Sales End Date'=>'Sales End Date',

	//Dashboard list of widgets translation
	'Open Tickets' => 'Open Tickets',
	'LBL_SELECT_STATUS' => 'Select Status',
	'LBL_BLANK' => '-Blank-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM honest Open Source',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Organization',
	'SINGLE_Contacts' => 'Contact',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Sun',
	'LBL_Mon' => 'Mon',
	'LBL_Tue' => 'Tue',
	'LBL_Wed' => 'Wed',
	'LBL_Thu' => 'Thu',
	'LBL_Fri' => 'Fri',
	'LBL_Sat' => 'Sat',

	//Months in 3 letters translations
	'LBL_Jan' => 'Jan',
	'LBL_Feb' => 'Feb',
	'LBL_Mar' => 'Mar',
	'LBL_Apr' => 'Apr',
	'LBL_May' => 'May',
	'LBL_Jun' => 'Jun',
	'LBL_Jul' => 'Jul',
	'LBL_Aug' => 'Aug',
	'LBL_Sep' => 'Sep',
	'LBL_Oct' => 'Oct',
	'LBL_Nov' => 'Nov',
	'LBL_Dec' => 'Dec',

	'LBL_CALENDAR_SETTINGS' => 'Calendar Settings',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'Organization',
	'SINGLE_Contacts' => 'Contact',
	'HelpDesk' => 'Tickets',
	'LBL_TAG_CLOUD' => 'Tag Cloud',

	'LBL_NO_RECORDS' => 'No Records',
	'LBL_NO_RELATED' => 'No Related',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Only the first 100 results of all modules are shown below. For module specific results, please select respective module and search',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Only the first 100 results are shown below. Please do Advanced Search if you are not satisfied with the result',

	// used in reports detail view
	'LBL_ACTION' => 'Action',
	'LBL_NOTE' => 'Note',
	'LBL_SELECT_OPTION' => 'Select an Option',

	//Module Manager
	'LBL_TOOLTIP' => 'Tooltip Management',
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Module Sequence Numbering',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Custom Field Mapping',
	'LBL_WEBFORMS' => 'WebForms',

	//Compose Email Strings
	'SINGLE_Emails' => 'Email',
	'Emails' => 'Emails',
	'LBL_SELECT_EMAIL_IDS' => 'Select Email Addresses',
	'LBL_SUBJECT' => 'Subject',
	'LBL_ATTACHMENT' => 'Attachment',
	'LBL_BROWSE_CRM' => 'Browse CRM',
	'LBL_SEND' => 'Send',
	'LBL_SAVE_AS_DRAFT' => 'Save as Draft',
	'LBL_GO_TO_PREVIEW' => 'Go to Preview',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Select Email Template',
	'LBL_COMPOSE_EMAIL' => 'Compose Email',
 	'LBL_CC' => 'Cc',
   	'LBL_BCC' => 'Bcc',
   	'LBL_ADD_CC' => 'Add Cc',
   	'LBL_ADD_BCC' => 'Add Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Maximum upload size is',
	'LBL_EXCEEDED' => 'Exceeded',
	'LBL_OPERATION_NOT_PERMITTED' => 'Operation not permitted',
    'LBL_MERGE' => 'Merge',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Merging Criteria Selection',
	'LBL_AVAILABLE_FIELDS' => 'Available Fields',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'The primary record will be retained after the merge. You can select the column to retain the values.
										The other record will be deleted but the related information will be merged.',
	'LBL_MERGE_RECORDS_IN' => 'Merge Records In',
	'LBL_FIELDS' => 'Fields',
	'LBL_RECORD' => 'Record',
	'LBL_NO_DUPLICATED_FOUND' => 'No duplicates found',
	'LBL_MERGE_SELECT' => 'Merge Select',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Back to products',

	//Translations used for Export to Pdf
	'Valid Date' => 'Valid Date',
	'Phone: ' => 'Phone: ',
	'Issued Date' => 'Issued Date',
	'Shipping & Handling Charges' => 'Shipping & Handling Charges',
	'Shipping & Handling Tax:' => 'Shipping & Handling Tax:',
	'Discount'=>'Discount',
	'Net Total' => 'Net Total',
	'Product Code'=>'Product Code',
	'Customer Name'=>'Customer Name',
	'Price'=>'Price',
	'Tax:' => 'Tax:',
	'Contact Name' => 'Contact Name',
	'Grand Total:' => 'Grand Total:',
	'Fax: ' => 'Fax: ',
	'Website: ' => 'Website: ',
	'Tax' => 'Tax',
	'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',

	//Realted tab strings
	'Service Contracts' => 'Service Contracts',
	'Projects' => 'Projects',
	'Sales Order' => 'Sales Order',
	'Purchase Order' => 'Purchase Order',
	'List and Campaigns' => 'List and Campaigns',
	'Project Tasks' => 'Project Tasks',
	'Project Milestones' => 'Project Milestones',

	'Labels Editor' => 'Labels Editor',
	'LBL_IGNORE_EMPTY_VALUES' =>'Ignore empty values',

	//Related tabs of Products
	'Product Bundles' => 'Product Bundles',
	'Parent Product' => 'Parent Product',

	'LBL_MANAGE_USERS' => 'Manage Users',
	'LBL_TRANSFER_OWNERSHIP' => 'Transfer Ownership',
	'LBL_SELECT_RELATED_MODULES' => 'Select Related Modules',
	'LBL_ASSIGNED_TO' => 'Assigned To',

	//Report Detail View
	'LBL_VIEW_DETAILS' => 'View Details',
	//Comments Field Labels for Workflow
	'Comment' => 'Comment',
	'Last Comment' => 'Last Comment',
	'Last 5 Comments' => 'Last 5 Comments',
	'All Comments' => 'All Comments',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Please configure your outgoing server settings from the settings page',
	'JS_SMS_SERVER_CONFIGURATION' => 'Please configure your SMS notifier from the SMS notifier settings page',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Please select at least one record',

	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Please enter a valid email address',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'contains illegal characters',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'phone number length exceeded limit',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Accepts only positive numbers',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'value should be greater than zero',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Number should be less than 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Please Enter Valid Date',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Please Enter Valid Time',
	'JS_INVALID_PAGE_NUMBER' => 'Invalid Page Number',


	'INVALID_NUMBER_OF' => 'Invalid number of',
	'INVALID_NUMBER' => 'Invalid number',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Are you sure that you want to delete?',

	'OVERWRITE_EXISTING_MSG1' => 'Overwrite the existing address with the selected ',
	'OVERWRITE_EXISTING_MSG2' => 'address details?',
	'SINGLE_Accounts' => 'Organization',
	'SINGLE_Contacts' => 'Contact',

	'LBL_DELETE_CONFIRMATION' => 'Are you sure you want to delete?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_MASS_DELETE_CONFIRMATION' => 'Are you sure you want to delete the selected Records?',
	'JS_LBL_SAVE' => 'Save',
	'JS_LBL_CANCEL' => 'Cancel',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Organization Name already Exists.Do you want to create a duplicate record?',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Must occur before today',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Please select at least one option',
	'JS_SELECT_MODULE' => 'Please Select Module',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Please select at least one Mandatory Field',
	'JS_SELECT_MODULE' => 'Please select a module',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Please enter integer value',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Please enter decimal value',

	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than Current Date',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'should be greater than Current Date',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'should be greater than or equal to',
    'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'should be less than or equal to',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Percentage value should be less than 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Accepts only numbers',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'This File has already been selected',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'max file Upload exceeds',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'This Document has already been attached',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'Should be greater than or equal to',


	//Roles
	'JS_FAILED_TO_SAVE' => 'Failed to save changes on server',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Import File cannot be Empty',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Select at least one field for merge criteria',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Map Name cannot be empty',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Map Name already exists',
	'JS_SELECT_FILE_EXTENSION' => 'Please select a file with the following extension:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Upload file size should be less than',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Uploaded file size exceeds',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Please split the file into smaller files and import again.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Field mapped more than once',
	'JS_MAP_MANDATORY_FIELDS' => 'Please map mandatory fields',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Please enter some value to search',

	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'You can select only',
	'JS_ITEMS' => 'items',

	'JS_LBL_PERMISSION' => 'Permissions',
	'JS_CHECK_FILE_INTEGRITY' => 'Check File Integrity',
	'JS_DUPLICATE_RECORD' => 'Duplicate Record',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'is enabled',
	'JS_IS_DISABLED' => 'is disabled',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Please enter some text for comment',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Comment value cannot be empty',
	'JS_REQUIRED_FIELD' => '* This field is required',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove Default Widget',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than Current Date',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'No create permissions or not enabled for quick create',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Image Deleted Successfully',
	'LBL_IMAGE_NOT_DELETED' => 'Image Not Deleted',
	'LBL_YES' => 'Yes',
	'LBL_NO' => 'No',
	'AM' => 'AM',
	'PM' => 'PM',
 	'JS_ERROR' => 'Error',
	'JS_INFORMATION' => 'Information',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'does not have an email address',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'None of the field values are changed in Mass Edit',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Please select an Organization to copy address',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Please select a Contact to copy address',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Organization does not contain address to copy',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Contact does not contain address to copy',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Please enter Primary email address to enable portal user',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Primary email field does not exist to enable portal user',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Please enter a tag',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Tag name already exist',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Tag length exceeds max size',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'No Records Related to this Filter',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Start Date & Time',
	'JS_END_DATE_TIME' => 'End Date & Time',
	'JS_POSTPONE' => 'Postpone',
	'JS_MESSAGE' => 'Message',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Shortcut added successfully',
	'JS_SUCCESSFULLY_UNPINNED' => 'Shortcut removed successfully',
	'JS_SHORTCUT_ALREADY_ADDED' => 'This shortcut is already added',
	'JS_MESSAGE' => 'Message',

	//Module Manager
	'JS_MODULE_ENABLED' => 'Module Enabled',
	'JS_MODULE_DISABLED' => 'Module Disabled',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Frequency of any cron job configured should not be less than',
	'JS_MINUTES' => 'mins',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Item Renamed Successfully',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Item added Successfully',
	'JS_NO_ITEM_SELECTED' => 'No item Selected',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'More than one Item selected',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Items Deleted Successfully',
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Select at least two records for merging',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'You are allowed to select a maximum of three records',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Are you sure to delete widget',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_TOTAL_RECORDS' => 'Total records',
	'JS_PAGE_NOT_EXIST' => 'Page not exist',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'You are in page number',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Please enable base currency for product',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Please select base currency for product',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Records are getting deleted',
	'JS_RECORD_GETTING_DELETED' => 'Record getting deleted',
	'JS_NO_RESULTS_FOUND' => 'No Results Found',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Records ownership has been tranferred successfully',

	'JS_USER_EXISTS' => 'User Already Exists',
	'JS_REENTER_PASSWORDS' => 'Renter Passwords',
);
